objects/Account.object
<CustomObject>
    <fields>
        <fullName>Depot_Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Depot Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Depot_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Depot Number</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Depot</fullName>
        <active>true</active>
        <description>Account for TNT Depots</description>
        <label>Depot</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Calendar__c.object
<CustomObject>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Day__c.object
<CustomObject>
    <fields>
        <fullName>Calendar__c</fullName>
        <label>Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Days</relationshipLabel>
        <relationshipName>Days</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Day_Type__c</fullName>
        <label>Day Type</label>
        <picklist>
            <picklistValues>
                <fullName>Working Day</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Working Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Day</label>
    <nameField>
        <label>Date</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Depot_Routing__c.object
<CustomObject>
    <fields>
        <fullName>Collection_Cut_Off_Time__c</fullName>
        <label>Collection Cut Off Time</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Collection depot – collection routings only</description>
        <inlineHelpText>Collection depot – collection routings only</inlineHelpText>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Depot Routings</relationshipLabel>
        <relationshipName>Depot_Routings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Division number – as an override- or blank for all divisions</description>
        <inlineHelpText>Division number – as an override- or blank for all divisions</inlineHelpText>
        <label>Line of Business</label>
        <referenceTo>Line_of_Business__c</referenceTo>
        <relationshipLabel>Depot Routings</relationshipLabel>
        <relationshipName>Depot_Routings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Round_Group__c</fullName>
        <label>Round Group</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Routing_Network__c</fullName>
        <label>Routing Network</label>
        <picklist>
            <picklistValues>
                <fullName>EXP</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EWW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RET</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Routing_Table__c</fullName>
        <label>Routing Table</label>
        <referenceTo>Routing_Table__c</referenceTo>
        <relationshipLabel>Depot Routings</relationshipLabel>
        <relationshipName>Depot_Routings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Depot Routing</label>
    <nameField>
        <displayFormat>DR-{00000000}</displayFormat>
        <label>Depot Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Routings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Line_of_Business__c.object
<CustomObject>
    <fields>
        <fullName>Routing_Network__c</fullName>
        <description>Type of routing network that the consignment will use. Certain goods must be handled by a specialist network of depots (e.g. Fashion).</description>
        <label>Routing Network</label>
        <picklist>
            <picklistValues>
                <fullName>EWW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RET</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Line of Business</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines of Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Routing_Table__c.object
<CustomObject>
    <fields>
        <fullName>Depot__c</fullName>
        <inlineHelpText>This is NOT the Collection Depot. Look in the Depot Routing section for the Collection Depot.

Routing Networks:
&gt; EXP = Express
&gt; EWW = International
&gt; RET = Fashion</inlineHelpText>
        <label>Depot</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Routings</relationshipLabel>
        <relationshipName>Routings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <externalId>true</externalId>
        <label>District</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Postcode__c</fullName>
        <externalId>true</externalId>
        <label>Part Postcode</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Routing Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Routing_Table__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Routing Table Reference</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <externalId>true</externalId>
        <label>Town</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Routing Table</label>
    <nameField>
        <displayFormat>RT-{00000000}</displayFormat>
        <label>Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OL_DepotRoutingHelper.cls
/**
* File Name   :    OL_DepotRoutingHelper.cls
* Description :    
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 04/09/2014 Klea Kolaric	TNT-542	find collection depot
*/
public with sharing class OL_DepotRoutingHelper {
	
	public static String errorMsg;
	public static Id routingTableId;
	public static Id depotRoutingId;
	public static String cutOffTime; 
	
	public static Account findCollectionDepot(String collPostcode, String collDistrict, String collTown, Id lobId, Datetime collTime)
	{
		// reset variables
		routingTableId = null;
		depotRoutingId = null;
		cutOffTime = null;
		
		errorMsg = '';
		errorMsg += String.isBlank(collPostcode) ? '- missing collection postcode<br/>' : '';
		errorMsg += String.isBlank(collTown) ? '- missing collection town<br/>' : '';
		errorMsg += lobId == null ? '- missing line of business<br/>' : '';
		errorMsg += collTime == null ? '- missing collection time<br/>' : '';
		if(String.isNotBlank(errorMsg))
		{
			errorMsg = 'Could not calculate depot:<br/>' + errorMsg;
			return null;
		}
		else
		{
			errorMsg = null;
		}
		
		Routing_Table__c rt = findRoutingTableEntry(collPostcode, collDistrict, collTown);
		
        if(rt == null)
		{
			errorMsg = 'No Routing Table entry found.';
			return null;
		}
		
		Day__c d = findDay(rt.Depot__r.Depot_Calendar__c,collTime);
		if(d == null)
		{
			errorMsg = 'No Calendar/Day entry found.';
			return null;
		}
		if(d.Day_Type__c.startsWith(ConstantUtil.PLVAL_DAY_DAYTYPE_NONWORKING))
		{
			errorMsg = 'Selected collection date is a non working day.';
			return null;
		}
		
		String roundGroup = d.Day_Type__c.startsWith(ConstantUtil.PLVAL_DAY_DAYTYPE_WORKING) 
			? ConstantUtil.PLVAL_DEPOTROUTING_ROUNDGROUP_NORMAL : ConstantUtil.PLVAL_DEPOTROUTING_ROUNDGROUP_SATURDAY;
		
		Account collDepot = findDepot(lobId, rt.Id, roundGroup);
		errorMsg = collDepot == null ? 'No depot found.' : null;
		routingTableId = collDepot == null ? null : rt.Id;
		return collDepot;
	}
	
	public static Routing_Table__c findRoutingTableEntry(String collPostcode, String collDistrict, String collTown)
	{
		if(String.isNotBlank(collPostcode) && collPostcode.length() > 3)
		{
			String pc = collPostcode;
	        pc = pc.substring(0, pc.length()-2);
			for(Routing_Table__c rtab : [select id, Depot__c, Depot__r.Depot_Calendar__c from Routing_Table__c 
											where Part_Postcode__c = :pc 
												and District__c = :collDistrict 
												and Town__c = :collTown 
											order by Routing_Default__c desc])	// default first
			{
				return rtab;
			}
		}
		return null;
	}
	
	public static Day__c findDay(Id calId, Datetime collTime)
	{
		for(Day__c d : [select Id, Day_Type__c from Day__c where Date__c = :collTime.date() and Calendar__c = :calId])
		{
			return d;
		}
		return null;
	}
	
	public static Account findDepot(Id lobId, Id rtId, String roundGroup)
	{
		String network = lobId == null ? null : [select Routing_Network__c from Line_of_Business__c where Id = :lobId limit 1].Routing_Network__c;
		for(Depot_Routing__c dr : [select Collection_Cut_Off_Time__c, Collection_Depot__c, Collection_Depot__r.Name, Collection_Depot__r.Depot_Number__c
									from Depot_Routing__c
									where Routing_Table__c = :rtId and Collection_Depot__c != null
										and (Line_Of_Business__c = :lobId or Line_Of_Business__c = null)
										and (Round_Group__c = :roundGroup or Round_Group__c = :ConstantUtil.PLVAL_DEPOTROUTING_ROUNDGROUP_ALL)
										and Routing_Network__c =:network
									order by Line_Of_Business__c asc nulls last])	// exact matches have precedence over nulls
		{
			depotRoutingId = dr.Id;
			cutOffTime = dr.Collection_Cut_Off_Time__c;
			return dr.Collection_Depot__r;
		}
		return null;
	}

}