objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <label>Street Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Account Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CS_Claims__c.object
<CustomObject>
    <description>TNT UK Claims Form Attachment Handling SR 2751</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Depot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Depot</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Claims (Depot)</relationshipLabel>
        <relationshipName>DepotClaims</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Depot_no__c</fullName>
        <inlineHelpText>Is auto populated from the Depot field when clicking &apos;Save&apos;.</inlineHelpText>
        <label>Depot no</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Address_1__c</fullName>
        <label>Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Address_2__c</fullName>
        <label>Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Address_3__c</fullName>
        <label>Town</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Contact_Name__c</fullName>
        <label>Contact name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Email_Address__c</fullName>
        <inlineHelpText>If the Contact above does not have an Email Address stored for them, you can enter one to use here.

If they do, then leave this field blank as it is auto populated from the Contact when clicking &apos;Save&apos;.</inlineHelpText>
        <label>Customer Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sender_Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Telephone_no__c</fullName>
        <label>Telephone no</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sender_company_name__c</fullName>
        <label>Company name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNT_account_no__c</fullName>
        <inlineHelpText>Is auto populated from the Account field when clicking &apos;Save&apos;.</inlineHelpText>
        <label>TNT account no</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>Claim Form</label>
    <nameField>
        <displayFormat>CLN-{000000}</displayFormat>
        <label>Claim Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Postcode__c.object
<CustomObject>
    <fields>
        <fullName>Postcode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Postcode</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Postcode</label>
    <nameField>
        <label>Postcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CS_ClaimsTriggerHandler.cls
/**
* File Name   :    CS_ClaimsTriggerHandler.cls
* Description :    methods called from CS_Claims trigger
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 16/07/2014 Liza Romanenko	Initial version
*
*/
public with sharing class CS_ClaimsTriggerHandler {
	
	// HANDLERS
	
	public static void onBeforeInsertHandler(List<CS_Claims__c> triggerNew)
	{
		fillDataFromRelatedObjects(triggerNew);	
	}
	
	public static void onAfterInsertHandler(List<CS_Claims__c> triggerNew)
	{
		
	}
	
	public static void onAfterUpdateHandler(List<CS_Claims__c> triggerNew, Map<Id,CS_Claims__c> triggerOldMap)
	{
		
	}

	public static void onBeforeUpdateHandler(List<CS_Claims__c> triggerNew, Map<Id,CS_Claims__c> triggerOldMap)
	{
		
	}
	
	// METHODS
	
	private static void fillDataFromRelatedObjects(List<CS_Claims__c> claims){
		Set<Id> accountIds = new Set<Id>();
		Set<Id> contactIds = new Set<Id>();
		
		for(CS_Claims__c c : claims){
			accountIds.add(c.Account__c);
			accountIds.add(c.Depot__c);
			contactIds.add(c.Contact__c);
		}
		
		Map<Id, Account> accounts = new Map<Id, Account>([SELECT Name, AccountNumber, BillingStreet, BillingState, BillingPostalCode,
																BillingCountry, BillingCity, Phone
															FROM Account WHERE Id IN : accountIds]);
		Map<Id, Contact> contacts = new Map<Id, Contact>([SELECT Name, Email, MailingStreet, MailingState, MailingPostalCode,
																MailingCountry, MailingCity, Phone
															FROM Contact WHERE Id IN : contactIds]);
		//Select Address Information
		Map<Id, Account_Address__c> aId_DefAddress = new Map<Id, Account_Address__c>();
		for(Account_Address__c aa : [SELECT Account__c, Street_1__c, Street_2__c, City__c, Postcode__c FROM Account_Address__c WHERE Account__c IN : accountIds AND Default__c = true]){
			aId_DefAddress.put(aa.Account__c, aa);
		}
		
		//fill fields in Claims
		for(CS_Claims__c c : claims){
			Account a = accounts.get(c.Account__c);
			Account d = accounts.get(c.Depot__c);
			Contact cont = contacts.get(c.Contact__c);
			Account_Address__c aa = aId_DefAddress.get(c.Account__c);
			
			c.TNT_account_no__c = a.AccountNumber;
			c.Sender_company_name__c = a.Name;
			if(aa != null){
				c.Sender_Address_1__c = aa.Street_1__c;
				c.Sender_Address_2__c = aa.Street_2__c;
				c.Sender_Address_3__c = aa.City__c;
				c.Sender_Postcode__c = aa.Postcode__c;
			}
			c.Sender_Telephone_no__c =   a.Phone;
			c.Depot_no__c = d.AccountNumber;
			if(cont != null){
				c.Sender_Contact_Name__c = cont.Name;
				if(c.Sender_Email_Address__c == null || c.Sender_Email_Address__c == ''){
					c.Sender_Email_Address__c = cont.Email;
				}
			}
			
		}
		
	}
}