objects/Account.object
<CustomObject>
    <fields>
        <fullName>Depot_Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Depot Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Depot_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Depot Number</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Operational_for_Bookings__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is used to mark any non operational depot&apos;s that should not be available for selection on the Booking &apos;Collection Depot&apos; field.  This field will then be used in the Lookup Filter Criteria along with the Depot Record Type</description>
        <inlineHelpText>Depots that are not operational for Bookings should be left unchecked.</inlineHelpText>
        <label>Operational for Bookings</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Account for TNT Clients</description>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Depot</fullName>
        <active>true</active>
        <description>Account for TNT Depots</description>
        <label>Depot</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses (Collection Depot)</relationshipLabel>
        <relationshipName>Account_Addresses2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>GBR</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Name__c</fullName>
        <label>Org Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Account Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Calendar__c.object
<CustomObject>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If a Collection Exception is selected then the Case will be assigned using the &apos;Collection Queue&apos; field for this Depot. 

Click on the Depot to see where this case would be assigned to.</inlineHelpText>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an account of type &apos;Depot&apos;.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Collection Depot)</relationshipLabel>
        <relationshipName>CollectionCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <inlineHelpText>Chose whether this Case is related to a Collection or Delivery issue. 

This info is then used with either the Collection Depot or Origin Depot fields respectively to Assign the case when the &apos;Assign using active assignment rules&apos; checkbox is ticked.</inlineHelpText>
        <label>Exception</label>
        <picklist>
            <picklistValues>
                <fullName>Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Day__c.object
<CustomObject>
    <fields>
        <fullName>Calendar__c</fullName>
        <label>Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Days</relationshipLabel>
        <relationshipName>Days</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Day_Type__c</fullName>
        <label>Day Type</label>
        <picklist>
            <picklistValues>
                <fullName>Working Day</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Working Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Day</label>
    <nameField>
        <label>Date</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Depot_Routing__c.object
<CustomObject>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Collection depot – collection routings only</description>
        <inlineHelpText>Collection depot – collection routings only</inlineHelpText>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Depot Routings</relationshipLabel>
        <relationshipName>Depot_Routings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Division number – as an override- or blank for all divisions</description>
        <inlineHelpText>Division number – as an override- or blank for all divisions</inlineHelpText>
        <label>Line of Business</label>
        <referenceTo>Line_of_Business__c</referenceTo>
        <relationshipLabel>Depot Routings</relationshipLabel>
        <relationshipName>Depot_Routings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Round_Group__c</fullName>
        <label>Round Group</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Routing_Network__c</fullName>
        <label>Routing Network</label>
        <picklist>
            <picklistValues>
                <fullName>EXP</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EWW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RET</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Routing_Table__c</fullName>
        <label>Routing Table</label>
        <referenceTo>Routing_Table__c</referenceTo>
        <relationshipLabel>Depot Routings</relationshipLabel>
        <relationshipName>Depot_Routings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Depot Routing</label>
    <nameField>
        <displayFormat>DR-{00000000}</displayFormat>
        <label>Depot Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Routings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Line_of_Business__c.object
<CustomObject>
    <fields>
        <fullName>Routing_Network__c</fullName>
        <description>Type of routing network that the consignment will use. Certain goods must be handled by a specialist network of depots (e.g. Fashion).</description>
        <label>Routing Network</label>
        <picklist>
            <picklistValues>
                <fullName>EWW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RET</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Line of Business</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines of Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Postcode__c.object
<CustomObject>
    <fields>
        <fullName>Postcode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Postcode</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Postcode</label>
    <nameField>
        <label>Postcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Routing_Table__c.object
<CustomObject>
    <fields>
        <fullName>Depot__c</fullName>
        <inlineHelpText>This is NOT the Collection Depot. Look in the Depot Routing section for the Collection Depot.

Routing Networks:
&gt; EXP = Express
&gt; EWW = International
&gt; RET = Fashion</inlineHelpText>
        <label>Depot</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Routings</relationshipLabel>
        <relationshipName>Routings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <externalId>true</externalId>
        <label>District</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Postcode__c</fullName>
        <externalId>true</externalId>
        <label>Part Postcode</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Routing Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Routing_Table__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Routing Table Reference</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <externalId>true</externalId>
        <label>Town</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Routing Table</label>
    <nameField>
        <displayFormat>RT-{00000000}</displayFormat>
        <label>Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestUtil.cls
/**
* File Name   :    TestUtil.cls
* Description :    help for testing
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 03/07/2014 Klea Kolaric	Initial version
*
*
*/
@isTest
public with sharing class TestUtil {
	
	public static Id accountClientRTId = [select id from RecordType where DeveloperName = 'Client' and sObjectType = 'Account' limit 1].id;
	public static Id accountDepotRTId = [select id from RecordType where DeveloperName = 'Depot' and sObjectType = 'Account' limit 1].id;
	
	public static Account createAccountClient()
	{
		Account a = new Account();
		a.recordTypeId = accountClientRTId;
		a.Name = 'Test Class Account';
		a.AccountNumber = '111';
		return a;
	}
	
	public static Account createAccountDepot()
	{
		Account a = new Account();
		a.recordTypeId = accountDepotRTId;
		a.Name = 'Test Class Depot';
		a.AccountNumber = '222';
        //Added by DH 23/10/15 to accomodate new field filter restraint
        a.Operational_for_Bookings__c = true;
		return a;
        
	}
	
	public static Contact createContact(Id accountId)
	{
		
        Contact c = new Contact();
		c.AccountId = accountId;
		c.FirstName = 'Test Class';
		c.LastName = 'Contact';
		c.Email = 'test@email.com';
		c.Phone = '1234554321';
		return c;
	}
	
	public static Case createCase(Id accountId, Id contactId, Id depotId)
	{
		// parsing error if first line populated (?????????)
		Case c = createCase(accountId, contactId);
		c.Collection_Depot__c = depotId;
		return c;
	}
	
	public static Case createCase(Id accountId, Id contactId)
	{
		// parsing error if first line populated (?????????)
		Case c = new Case();
		c.Subject = 'Test Class Case';
		c.Description = 'test class';
		c.AccountId = accountId;
		c.ContactId = contactId;
		c.Exception__c = ConstantUtil.PLVAL_CASE_EXCEPTION_COLLECTION;
		return c;
	}
	
	public static Account_Address__c createAccountAddress(Id accountId, Id contactId)
	{
		Account_Address__c aa = new Account_Address__c();
		aa.Account__c = accountId;
		aa.Contact__c = contactId;
		aa.Org_Name__c = 'test address ' + Math.rint(Math.random()*1000);
		aa.Street_1__c = 'my test street';
		aa.Postcode__c = 'SW15 1TW';
		aa.City__c = 'Testville';
		aa.Country__c = ConstantUtil.ISOCODE_UK;
		return aa;
	}
	
	public static Campaign createCampaign()
	{
		Campaign c = new Campaign();
		c.isActive = true;
		c.Name = 'testCampaign';
		c.Status = 'In Progress';
		c.StartDate = Date.today().addDays(-7);
		c.EndDate = Date.today().addDays(7);
		c.Description = 'my test campaign';
		return c;
	}
	
	public static CampaignMember createCampaignMember(Id campaignId, Id contactId)
	{
		CampaignMember cm = new CampaignMember();
		cm.CampaignId = campaignId;
		cm.ContactId = contactId;
		cm.Status = 'Sent';
		return cm;
	}
	
	public static User createAgentUser() {

		Profile p = [SELECT Id FROM Profile WHERE Name='CS Agent']; 
		return createUser(p.Id,null);
	}
	
	public static User createAdminUser() {

		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
		return createUser(p.Id,null);
	}
	
	public static User createIntegrationUser() {

		Profile p = [SELECT Id FROM Profile WHERE Name='Integration User']; 
		return createUser(p.Id,null);
	}
	
	public static User createUser(Id profileId, Id roleId) {

		User u = new User(Alias = 'standt', Email='test@example.com', 
		EmailEncodingKey='UTF-8', LastName='Testing',  
		LocaleSidKey='en_US', LanguageLocaleKey='en_US', 
		ProfileId = profileId, UserRoleId = roleId, 
		TimeZoneSidKey='America/Los_Angeles', UserName='tntuser@example.com');

		return u;
	}
	
	public static List<sObject> proxyInsert(List<sObject> sobjs)	// use this to avoid mixing insert of setup and non-setup sobject
	{
		System.runAs(new User(Id = UserInfo.getUserId()))
		{
			insert sobjs;
		}
		return sobjs;
	}
	
	// create entry with working day and normal depot
	public static Account setupDepotRouting(Id lobId, Account_Address__c aa, Date collDate)
	{
		Account depot = createAccountDepot();
		Account dep1 = createAccountDepot();		// calendar linking depot
		dep1.AccountNumber = '999';
		dep1.Depot_Number__c = '999';
		dep1.Name += '999';
		insert new List<Account>{depot,dep1};

		Calendar__c cal = new Calendar__c();
		cal.Name = 'Default Calendar';
		insert cal;
		Day__c d = new Day__c();
		d.Calendar__c = cal.id;
		d.Date__c = collDate;
		d.Name = collDate.format();
		d.Day_Type__c = ConstantUtil.PLVAL_DAY_DAYTYPE_WORKING;
		insert d;

		dep1.Depot_Calendar__c = cal.id;
		update dep1;

		Routing_Table__c rt = new Routing_Table__c();
		rt.Depot__c = dep1.id;
		rt.Routing_Default__c = true;
		rt.District__c = aa.District__c;
		rt.Town__c = aa.City__c;
		rt.Part_Postcode__c = aa.Postcode__c.substring(0, aa.Postcode__c.length()-2);
		insert rt;

		Depot_Routing__c dr = new Depot_Routing__c();
		dr.Collection_Depot__c = depot.id;
		dr.Line_of_Business__c = lobId;
		dr.Round_Group__c = ConstantUtil.PLVAL_DEPOTROUTING_ROUNDGROUP_NORMAL;
		dr.Routing_Table__c = rt.Id;
		dr.Routing_Network__c = 'EXP';
		insert dr;

		return depot;
	}
	
	public static void setupBusinessHoursAndHolidays()
	{
		TimeUtil.bh = newBusinessHours();
		TimeUtil.holidays = newHolidays();
	}
	
	public static BusinessHours newBusinessHours()
	{
		return new BusinessHours(
						Name='Default',
						MondayStartTime=Time.newInstance(8,0,0,0), MondayEndTime=Time.newInstance(18,0,0,0),	// 8-18
						TuesdayStartTime=Time.newInstance(8,0,0,0), TuesdayEndTime=Time.newInstance(18,0,0,0), 	// 8-18
						WednesdayStartTime=Time.newInstance(0,0,0,0), WednesdayEndTime=Time.newInstance(0,0,0,0), 	// all day
						ThursdayStartTime=Time.newInstance(8,0,0,0), ThursdayEndTime=Time.newInstance(18,0,0,0),	// 8-18
						FridayStartTime=Time.newInstance(8,0,0,0), FridayEndTime=Time.newInstance(17,30,0,0), 	// 8-17:30
						SaturdayStartTime=Time.newInstance(9,0,0,0), SaturdayEndTime=Time.newInstance(17,30,0,0), 	// 9-17:30
						SundayStartTime=null, SundayEndTime=null, 	// not a work day
						IsDefault=true, 
						IsActive=true,
						TimeZoneSidKey='Europe/London');
	}
	
	public static List<Holiday> newHolidays()
	{
		List<Holiday> hds = new List<Holiday>();
		hds.add(new Holiday(
						Name='Random Holiday',
						ActivityDate=Date.newInstance(2014,4,2), 	// random holiday on April 2nd 2014 (Wednesday)
						IsRecurrence=false, 
						RecurrenceType=null, 
						RecurrenceMonthOfYear=null, 
						RecurrenceDayOfWeekMask=null, 
						RecurrenceDayOfMonth=null,
						RecurrenceInstance=null, 
						IsAllDay=true));
		hds.add(new Holiday(
						Name='First Friday in May Holiday',
						ActivityDate=Date.newInstance(2014,5,2), 	// holiday on May 2nd 2014 (Friday)
						IsRecurrence=true, 
						RecurrenceType=ConstantUtil.HOLIDAY_RECTYPE_YEARLYNTH, 
						RecurrenceMonthOfYear=ConstantUtil.MONTHS_I2S.get(5), 
						RecurrenceDayOfWeekMask=32, // Friday bitmask
						RecurrenceDayOfMonth=null,
						RecurrenceInstance=ConstantUtil.HOLIDAY_RECINSTANCE_FIRST, // first Friday in May
						IsAllDay=true));
		hds.add(new Holiday(
						Name='Second Friday in May Holiday',
						ActivityDate=Date.newInstance(2014,5,9), 	// holiday on May 9th 2014 (Friday)
						IsRecurrence=true, 
						RecurrenceType=ConstantUtil.HOLIDAY_RECTYPE_YEARLYNTH, 
						RecurrenceMonthOfYear=ConstantUtil.MONTHS_I2S.get(5), 
						RecurrenceDayOfWeekMask=32, // Friday bitmask
						RecurrenceDayOfMonth=null,
						RecurrenceInstance=ConstantUtil.HOLIDAY_RECINSTANCE_SECOND, // second Friday in May
						IsAllDay=true));
		hds.add(new Holiday(
						Name='Third Friday in May Holiday',
						ActivityDate=Date.newInstance(2014,5,16), 	// holiday on May 16th 2014 (Friday)
						IsRecurrence=true, 
						RecurrenceType=ConstantUtil.HOLIDAY_RECTYPE_YEARLYNTH, 
						RecurrenceMonthOfYear=ConstantUtil.MONTHS_I2S.get(5), 
						RecurrenceDayOfWeekMask=32, // Friday bitmask
						RecurrenceDayOfMonth=null,
						RecurrenceInstance=ConstantUtil.HOLIDAY_RECINSTANCE_THIRD, // third Friday in May
						IsAllDay=true));
		hds.add(new Holiday(
						Name='Fourth Friday in May Holiday',
						ActivityDate=Date.newInstance(2014,5,23), 	// holiday on May 23rd 2014 (Friday)
						IsRecurrence=true, 
						RecurrenceType=ConstantUtil.HOLIDAY_RECTYPE_YEARLYNTH, 
						RecurrenceMonthOfYear=ConstantUtil.MONTHS_I2S.get(5), 
						RecurrenceDayOfWeekMask=32, // Friday bitmask
						RecurrenceDayOfMonth=null,
						RecurrenceInstance=ConstantUtil.HOLIDAY_RECINSTANCE_FOURTH, // fourth Friday in May
						IsAllDay=true));
		hds.add(new Holiday(
						Name='Last Friday in May Holiday',
						ActivityDate=Date.newInstance(2014,5,30), 	// holiday on May 30th 2014 (Friday)
						IsRecurrence=true, 
						RecurrenceType=ConstantUtil.HOLIDAY_RECTYPE_YEARLYNTH, 
						RecurrenceMonthOfYear=ConstantUtil.MONTHS_I2S.get(5), 
						RecurrenceDayOfWeekMask=32, // Friday bitmask
						RecurrenceDayOfMonth=null,
						RecurrenceInstance=ConstantUtil.HOLIDAY_RECINSTANCE_LAST, // last Friday in May
						IsAllDay=true));
		hds.add(new Holiday(
						Name='Christmas',
						ActivityDate=Date.newInstance(2014,12,25), 	// holiday on Dec 25th (Thursday)
						IsRecurrence=true, 
						RecurrenceType=ConstantUtil.HOLIDAY_RECTYPE_YEARLY, 
						RecurrenceMonthOfYear=ConstantUtil.MONTHS_I2S.get(12), 
						RecurrenceDayOfWeekMask=null,
						RecurrenceDayOfMonth=25,
						RecurrenceInstance=null,
						IsAllDay=true));
		hds.add(new Holiday(
						Name='Boxing Day',
						ActivityDate=Date.newInstance(2014,12,26), 	// holiday on Dec 26th (Friday)
						IsRecurrence=true, 
						RecurrenceType=ConstantUtil.HOLIDAY_RECTYPE_YEARLY, 
						RecurrenceMonthOfYear=ConstantUtil.MONTHS_I2S.get(12), 
						RecurrenceDayOfWeekMask=null,
						RecurrenceDayOfMonth=26,
						RecurrenceInstance=null,
						IsAllDay=true));
		
		return hds;
	}
}