objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Dangerous_Goods__c</fullName>
        <description>does a customer ship dangerous goods?</description>
        <label>Ships Dangerous Goods</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <formula>IF(ISBLANK(Account__c),&apos;&apos;,Account__r.Account_Number__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Carriage_Forward__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Carriage Forward</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collection_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Collection Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Collection_Postcode__c</fullName>
        <description>Collection postcode</description>
        <label>Collection: Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dangerous_Goods__c</fullName>
        <defaultValue>false</defaultValue>
        <description>is this a shipment of dangerous goods?</description>
        <label>Dangerous Goods</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <description>Received from Responce</description>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Postcode__c</fullName>
        <description>Delivery postcode</description>
        <label>Delivery: Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enhanced_Liability_Option__c</fullName>
        <description>The Tier/Level of Enhanced Liability selected by the customer for a Booking/Quote</description>
        <inlineHelpText>What level of Enhanced Liability does the customer want for this quote?</inlineHelpText>
        <label>Enhanced Liability Option</label>
        <picklist>
            <picklistValues>
                <fullName>0 - None</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1 - £3.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - £6.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - £9.00</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fuel_Supplement__c</fullName>
        <inlineHelpText>The Fuel Supplement should be entered only when you receive communication of a rate change.  If left blank a default value is used in the quotation.</inlineHelpText>
        <label>Fuel Supplement</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Is_Guaranteed_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Receive from Responce</description>
        <label>Is Guaranteed Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Premium_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Receive from Responce</description>
        <label>Is Premium Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Long_Length_Items__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Stores the number of Long Length Items that have been entered on the Quote Line Items Over 160cm in any dimension.  This value is calculated within the code on record Edit and is set when the user clicks Save. (See OL_BookingQuoteHelper.cls)</description>
        <label>No. Long Length Items</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pallet_Pollicy__c</fullName>
        <label>Pallet Pollicy</label>
        <summaryFilterItems>
            <field>Quote_Line_Item__c.Pallet_Policy__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Quote_Line_Item__c.Quote__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reason_for_Not_Booking__c</fullName>
        <label>Reason for Not Booking</label>
        <picklist>
            <picklistValues>
                <fullName>Customer to book via CIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incompatible traffic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need to confirm with bill payer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need to confirm with receiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Old rate removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Too expensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to offer EL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to offer required service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <description>Name of service that was selected for Quote</description>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplements_Details__c</fullName>
        <description>Supplements included in Price.  Get from Response.</description>
        <label>Supplements Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_Items__c</fullName>
        <label>Total Number of Items</label>
        <summarizedField>Quote_Line_Item__c.Number_of_Items__c</summarizedField>
        <summaryForeignKey>Quote_Line_Item__c.Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Volume_Rounded__c</fullName>
        <description>Total Volume rounded to 3 decimal places. It is the same as the Volume field but has been kept as it is used in the Quote integration to send the volume amount. We could remove this field in future but would require the interface to be updated also.</description>
        <formula>Total_Volume__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Volume Rounded</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Weight__c</fullName>
        <label>Total Weight (kg)</label>
        <summarizedField>Quote_Line_Item__c.Total_Weight__c</summarizedField>
        <summaryForeignKey>Quote_Line_Item__c.Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>QR{000000}</displayFormat>
        <label>Quote Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Service_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique code of the Service.</description>
        <externalId>true</externalId>
        <label>Service Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TNT_Integration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>TNT Integration</label>
</CustomObject>

classes/OL_GetQuotePricingDetailsExtension.cls
/**
* File Name   :    OL_GetQuotePricingDetailsExtension.cls
* Description :    
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 07/08/2014 Liza Romanenko Initial version, TNT-545
*/
public with sharing class OL_GetQuotePricingDetailsExtension {
    
    public Quote__c quote;
        
    public uksvcsTntGetQuotePricing.Deliveries_ContainerType responceData {get; set;}
    
    public Map<String, Service__c> services {get; set;}
    public String serviceKeys {get; set;}
    public Boolean errorOnLoad {get; private set;}
    private Apexpages.standardController sc;

    public OL_GetQuotePricingDetailsExtension(Apexpages.standardController stdCtrl){
        sc = stdCtrl;
        Id qId = stdCtrl.getRecord().Id;
        
        if(qId != null){
            quote = [SELECT Name, Price__c, Total_Number_of_Items__c, Total_Volume_Rounded__c, Total_Weight__c, Collection_Date__c, Collection_Postcode__c,
                    Delivery_Postcode__c, Account__r.Account_Number__c, Dangerous_Goods__c, Pallet_Pollicy__c, Carriage_Forward__c, Enhanced_Liability_Option__c,
                    Fuel_Supplement__c, Service_Name__c, Is_Guaranteed_Service__c, Is_Premium_Service__c, Delivery_Date__c, Supplements_Details__c, No_Long_Length_Items__c 
                FROM Quote__c WHERE Id = : qId];
        }
        errorOnLoad = false;
        
        fillServices();
    }
    
    public void requestPrice(){
        
        try{
            errorOnLoad = false;
            uksvcsTntGetQuotePricingService.getPricingDetailsForQuotePort port = new uksvcsTntGetQuotePricingService.getPricingDetailsForQuotePort();
            
            port.inputHttpHeaders_x = new map<string,string> {'Username' => TNT_Integration__c.getInstance().Username__c, 
                                                              'Password' => TNT_Integration__c.getInstance().Password__c};
            
            uksvcsTntComGenericPayloadHeader.payloadHeader 
                hdr = new uksvcsTntComGenericPayloadHeader.payloadHeader();
            uksvcsTntGetQuotePricing.QuoteRequest_MasterType
                con = new uksvcsTntGetQuotePricing.QuoteRequest_MasterType ();
            
            if(quote.Account__r.Account_Number__c != null) {
                con.actNum = quote.Account__r.Account_Number__c;
            }
            con.rqstdColDt = quote.Collection_Date__c;
            con.colPstCd = quote.Collection_Postcode__c;
            con.delPstCd = quote.Delivery_Postcode__c;
            con.totItms = String.valueOf(quote.Total_Number_of_Items__c);
            con.totVol = String.valueOf(quote.Total_Volume_Rounded__c);
            con.totActWght = String.valueOf(quote.Total_Weight__c);
            con.wghtUOM = 'KG';
            con.hazGdInd = quote.Dangerous_Goods__c;
            con.plltInd = quote.Pallet_Pollicy__c > 0 ? true : false;
            con.crrgFwdInd = quote.Carriage_Forward__c;
            con.enhLbltyInd = (quote.Enhanced_Liability_Option__c == ConstantUtil.PLVAL_QUOTE_ENHANCED_LIABILITY_OPTION_NONE || quote.Enhanced_Liability_Option__c == null) ? false : true;
            
            con.LongLengths = String.valueOf(quote.No_Long_Length_Items__c);
            
            if(quote.Fuel_Supplement__c != null) {
                con.fuelSrchrg = String.valueOf(quote.Fuel_Supplement__c);
            }
            
            uksvcsTntGetQuotePricing.ResponseMessage_MasterType resp;
            
            if(!ConstantUtil.INTEGRATION_ACCESS) throw new ConstantUtil.IntegrationAccessDeniedException(ConstantUtil.INTEGRATION_EXMSG);
            port.timeout_x = ConstantUtil.INTEGRATION_TIMEOUT;
            resp = port.getPricingDetailsForQuote(hdr, con);
            
            if(resp.qt != null && resp.qt.dels != null){
                responceData =  resp.qt.dels;
            } 
            else
            {
                errorOnLoad = true;
            }
            
            if(resp.hdr != null && resp.hdr.infoMsg != null){
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, resp.hdr.infoMsg));
            }
        } catch (Exception ex) {
            Apexpages.addMessages(ex);
            responceData = new uksvcsTntGetQuotePricing.Deliveries_ContainerType();
            errorOnLoad = true;
        }
        
    }
    
    public PageReference savePrice(){
        try{
            for(uksvcsTntGetQuotePricing.Delivery_MasterType dt : responceData.del) {
                if(dt.selected){
                    for(uksvcsTntGetQuotePricing.DeliveryService_MasterType ds : dt.delSvcs.delSvc){
                        if(ds.selected){
                            //get service Name
                            List<Service__c> service = [SELECT Name FROM Service__c WHERE Service_Code__c = : ds.svcCd]; 
                            quote.Delivery_Date__c = dt.delDt;
                            quote.Service_Name__c = (service != null && !service.isEmpty()) ? service[0].Name : ds.svcCd;
                            quote.Is_Guaranteed_Service__c = ds.guarSvcInd;
                            quote.Is_Premium_Service__c = ds.prSvcInd;
                            quote.Price__c = Decimal.valueOf(ds.qtAmt);
                            String supplementsDetails = '';
                            for(uksvcsTntGetQuotePricing.Surcharge_MasterType sd : ds.srchrgs.srchrg){
                                supplementsDetails += sd.srchrgTypCd + ' \t' + sd.srchrgTypNm;
                                supplementsDetails += String.isEmpty(sd.chrgAmt) ? '' : ' \t' + sd.chrgAmt + ' ' + sd.curCd;
                                supplementsDetails += String.isEmpty(sd.chrgPrcnt) ? '' : ' \t' + sd.chrgPrcnt + '%';
                                supplementsDetails += '\n';
                            }
                            quote.Supplements_Details__c = supplementsDetails;
                                                       
                            quote.Reason_for_Not_Booking__c = ((Quote__c)sc.getRecord()).Reason_for_Not_Booking__c;
                            
                            upsert quote;
                            return new PageReference('/' + quote.Id);
                        }
                    }
                    break;
                }
            }
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Please select service.'));
        } catch(Exception ex){
            Apexpages.addMessages(ex);
        }
        return null;
    }
    
    public PageReference cancel(){
        
        return new PageReference('/' + quote.Id);
    }
    
    public void fillServices() {
        services = new Map<String, Service__c>();
        serviceKeys = '';
            
        for(Service__c a : [SELECT Name, Service_Code__c FROM Service__c 
                WHERE Service_Code__c != null ORDER BY Name]){
            services.put(a.Service_Code__c, a);
            serviceKeys += '*' + a.Service_Code__c + '*';
        }       
        
    }
    

}