objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Depot</fullName>
        <active>true</active>
        <description>Account for TNT Depots</description>
        <label>Depot</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses (Collection Depot)</relationshipLabel>
        <relationshipName>Account_Addresses2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Account Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Coll_Account_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Address</label>
        <referenceTo>Account_Address__c</referenceTo>
        <relationshipLabel>Bookings (Collection Account Address)</relationshipLabel>
        <relationshipName>CollectionBookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings (Collection Contact)</relationshipLabel>
        <relationshipName>CC_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Auto populated by routing table logic</description>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Collection Depot must be an Account of type &quot;Depot&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <filterItems>
                <field>Account.Operational_for_Bookings__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings (Collection Depot)</relationshipLabel>
        <relationshipName>ColDepBookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commodity__c</fullName>
        <description>Value restricted by LOB Selected</description>
        <label>Type of packaging</label>
        <picklist>
            <picklistValues>
                <fullName>TSL 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assorted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Envelope</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dangerous Goods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incompatible Traffic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiffy Bag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Length</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pallet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roll</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings (Order Contact)</relationshipLabel>
        <relationshipName>OC_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Not Collected</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated to Round</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
                <color>#000000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#BBBBBB</color>
            </picklistValues>
            <picklistValues>
                <fullName>Collected</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected to Customer Services</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Items__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Auto populated from sum of line items, can be overridden</description>
        <label>Total Items</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Volume__c</fullName>
        <label>Total Volume</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Weight__c</fullName>
        <description>Auto populated from sum of line items, can be overridden</description>
        <label>Total Weight</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Booking_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Line_Item_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Booking Line Item Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Booking Line Items</relationshipLabel>
        <relationshipName>Booking_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <description>Field to save one item&apos;s height in meters</description>
        <inlineHelpText>Item height in meters</inlineHelpText>
        <label>Height (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <description>Field to save one item&apos;s length in meters</description>
        <inlineHelpText>Item length in meters</inlineHelpText>
        <label>Length (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <label>Number of Items</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Field to save one item&apos;s weight in kilograms</description>
        <inlineHelpText>Item weight in kilograms</inlineHelpText>
        <label>Weight (kg)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <description>Field to save one item&apos;s width in meters</description>
        <inlineHelpText>Item width in meters</inlineHelpText>
        <label>Width (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>Line-{0000}</displayFormat>
        <label>Booking Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BookingLineItemTriggerHelperTest.cls
/**
* File Name   :    BookingLineItemTriggerHelperTest.cls
* Description :    
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 08/09/2014 Klea Kolaric	Initial Version TNT-1604
* 0.2 23/10/2015 Darryl Hopper	Added and amended code where DH comments to turn off new duplicate checks
*/
@isTest
private class BookingLineItemTriggerHelperTest {

	static Booking__c createBaseBooking(String id)
	{
		//DH added 23/10/15 to allow duplicates whilst testing
        Database.DMLOptions dml = new Database.DMLOptions();
		dml.DuplicateRuleHeader.AllowSave = true; 
        //
        
        Account a = TestUtil.createAccountClient();
		insert a;
		Account_Address__c aaCol = TestUtil.createAccountAddress(a.Id,null);
		aaCol.Default__c = true;
		insert aaCol;
		Contact con = TestUtil.createContact(a.Id);
		con.FirstName = con.FirstName + id;
		//Modified by DH to use database method instead of insert to alow turn off duplicate checking for testing
        database.insert(con,dml);
        //insert con;
		Account depot = TestUtil.createAccountDepot();
		insert depot;
		
		Booking__c bo = new Booking__c();
		bo.Name = 'test book';
		bo.Account__c = a.Id;
		bo.Order_Contact__c = con.Id;
		bo.Collection_Contact__c = con.Id;
		bo.Coll_Account_Address__c = aaCol.id;
		bo.Collection_Depot__c = depot.id;
		bo.Commodity__c = 'SACK';
		bo.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		return bo;
	}
	
	// trigger coverage
    static testMethod void quickRun()
    {
		Booking__c bo = createBaseBooking(null);
		insert bo;
		
		Booking_Line_Item__c bli = new Booking_Line_Item__c(Booking__c = bo.id);
		bli.Weight__c = 20;
		bli.Number_of_Items__c = 1;
		bli.Height__c = 100;
		bli.Length__c = 100;
		bli.Width__c = 100;
		
		Test.startTest();
		insert bli;
		update bli;
		delete bli;
		Test.stopTest();
    }
    
    static testMethod void testUpdateBookingTotals()
    {
		//Added by DH 23/10/15 
        Database.DMLOptions dml = new Database.DMLOptions();
		dml.DuplicateRuleHeader.AllowSave = true; 
        Booking__c bo1 = createBaseBooking(null);	// will ovewrite null
		bo1.Total_Items__c = null;
		bo1.Total_Weight__c = null;
		Booking__c bo2 = createBaseBooking('c1');	// will overwrite less
		bo2.Total_Items__c = 1;
		bo2.Total_Weight__c = 1;
		Booking__c bo3 = createBaseBooking('c2');	// will not overwrite more
		bo3.Total_Items__c = 1000;
		bo3.Total_Weight__c = 1000;
		insert new List<Booking__c>{bo1,bo2,bo3};
		
		Double weight = 20;
		Double noItems = 3;
		List<Booking_Line_Item__c> blis = new List<Booking_Line_Item__c>();
		
		blis.add(new Booking_Line_Item__c(Booking__c = bo1.id, Weight__c = weight, Number_of_Items__c = noItems, 
					Length__c = 10, Width__c = 10, Height__c = 10, Booking_Line_Item_Id__c = '000'));
		blis.add(new Booking_Line_Item__c(Booking__c = bo2.id, Weight__c = weight, Number_of_Items__c = noItems, 
					Length__c = 10, Width__c = 10, Height__c = 10, Booking_Line_Item_Id__c = '001'));
		blis.add(new Booking_Line_Item__c(Booking__c = bo3.id, Weight__c = weight, Number_of_Items__c = noItems, 
					Length__c = 10, Width__c = 10, Height__c = 10, Booking_Line_Item_Id__c = '010'));
		blis.add(new Booking_Line_Item__c(Booking__c = bo1.id, Weight__c = weight, Number_of_Items__c = 0, 
					Booking_Line_Item_Id__c = '011'));
		blis.add(new Booking_Line_Item__c(Booking__c = bo2.id, Weight__c = weight, Number_of_Items__c = 0, 
					Length__c = 10, Width__c = 10, Height__c = 10, Booking_Line_Item_Id__c = '100'));
		blis.add(new Booking_Line_Item__c(Booking__c = bo3.id, Weight__c = weight, Number_of_Items__c = 0, 
					Length__c = 10, Width__c = 10, Height__c = 10, Booking_Line_Item_Id__c = '101'));
		blis.add(new Booking_Line_Item__c(Booking__c = bo1.id, Weight__c = null, Number_of_Items__c = noItems, 
					Length__c = 10, Width__c = 10, Height__c = 10, Booking_Line_Item_Id__c = '111'));
		blis.add(new Booking_Line_Item__c(Booking__c = bo2.id, Weight__c = null, Number_of_Items__c = noItems, 
					Length__c = 10, Width__c = 10, Height__c = 10, Booking_Line_Item_Id__c = '222'));
		blis.add(new Booking_Line_Item__c(Booking__c = bo3.id, Weight__c = null, Number_of_Items__c = noItems, 
					Length__c = 10, Width__c = 10, Height__c = 10, Booking_Line_Item_Id__c = '333'));
		
		User u = TestUtil.createIntegrationUser();	// avoid all validation rules
		insert u;
		
		Test.startTest();
		System.runAs(u) { insert blis; }
		Test.stopTest();
		
		Double vol = 10*10*10*noItems*2;
		system.assertEquals(1,[select count() from Booking__c
			where id = :bo1.id and Total_Items__c = :2*noItems and Total_Weight__c = :noItems*weight and Total_Volume__c = :vol]);
		system.assertEquals(1,[select count() from Booking__c 
			where id = :bo2.id and Total_Items__c = :2*noItems and Total_Weight__c = :noItems*weight and Total_Volume__c = :vol]);
		system.assertEquals(1,[select count() from Booking__c 
			where id = :bo3.id and Total_Items__c = :bo3.Total_Items__c and Total_Weight__c = :bo3.Total_Weight__c and Total_Volume__c = :vol]);
    }
}