objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auto_Case_Creation__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If Checked then cases are auto created for this account if any associated bookings are &apos;Rejected to Customer Services&apos;. 

The box is automatically Unchecked when an Account becomes a Major Account and vice versa.</description>
        <inlineHelpText>If Checked then cases are auto created for this account if any associated bookings are &apos;Rejected to Customer Services&apos;. 

The box is automatically Unchecked when an Account becomes a Major Account and vice versa.</inlineHelpText>
        <label>Auto Case Creation</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Depot</fullName>
        <active>true</active>
        <description>Account for TNT Depots</description>
        <label>Depot</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses (Collection Depot)</relationshipLabel>
        <relationshipName>Account_Addresses2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Account Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_LOB__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account LOBs</relationshipLabel>
        <relationshipName>Account_LOBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Collection_Date__c</fullName>
        <label>Last Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Line of Business</label>
        <referenceTo>Line_of_Business__c</referenceTo>
        <relationshipLabel>Account LOBs</relationshipLabel>
        <relationshipName>Account_LOBs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account LOB</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Account LOB Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account LOBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Booking_Id__c</fullName>
        <externalId>true</externalId>
        <label>Booking Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Booking_Rejected_by_Depot__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is checked when a depot rejects a booking. A reason for this rejection should be provided as a text comment with the rejection.</description>
        <label>Booking Rejected by Depot</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Auto populated by routing table logic</description>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Collection Depot must be an Account of type &quot;Depot&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <filterItems>
                <field>Account.Operational_for_Bookings__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings (Collection Depot)</relationshipLabel>
        <relationshipName>ColDepBookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commodity__c</fullName>
        <description>Value restricted by LOB Selected</description>
        <label>Type of packaging</label>
        <picklist>
            <picklistValues>
                <fullName>TSL 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assorted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Envelope</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dangerous Goods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incompatible Traffic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiffy Bag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Length</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pallet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roll</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Restricted by Line of Buisness on Account (Account_LOB__c)</description>
        <label>Line of Business (Division)</label>
        <referenceTo>Line_of_Business__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings (Order Contact)</relationshipLabel>
        <relationshipName>OC_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Depot_Rejection__c</fullName>
        <description>When a depot rejects a booking, they need to check the &apos;Booking Rejected by Depot&apos; field, which will raise a case. A reason for this rejection should be provided as a text comment with the rejection.</description>
        <inlineHelpText>What is the reason for the Depot rejecting the booking?</inlineHelpText>
        <label>Reason for Depot Rejection</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Not Collected</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated to Round</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
                <color>#000000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#BBBBBB</color>
            </picklistValues>
            <picklistValues>
                <fullName>Collected</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected to Customer Services</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Booking_Id_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Current_Number__c</fullName>
        <label>Current Number</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prefix__c</fullName>
        <label>Prefix</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Booking Id Settings</label>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup field to a Booking so that case can be related to a specific booking e.g. for failed collections</description>
        <inlineHelpText>Is this case related to a Booking?</inlineHelpText>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If a Collection Exception is selected then the Case will be assigned using the &apos;Collection Queue&apos; field for this Depot. 

Click on the Depot to see where this case would be assigned to.</inlineHelpText>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an account of type &apos;Depot&apos;.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Collection Depot)</relationshipLabel>
        <relationshipName>CollectionCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Line_of_Business__c.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business_Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique reference for the line of Business.</description>
        <externalId>true</externalId>
        <label>Line of Business Reference</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Line of Business</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines of Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Postcode__c.object
<CustomObject>
    <fields>
        <fullName>Postcode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Postcode</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Postcode</label>
    <nameField>
        <label>Postcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BookingTriggerHandlerTest.cls
/**
* File Name   :    BookingTriggerHandlerTest.cls
* Description :    Test class for BookingTriggerHandler
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 24/07/2014 Liza Romanenko	Initial version
* 0.2 29/08/2014 Liza Romanenko add test for generateBookingId() method TNT-1414
*
*/
@isTest
private class BookingTriggerHandlerTest {
	
	/* tested code is depricated 9 Apr 2015. 
    static testMethod void testBookingRejection() {

        Account a = TestUtil.createAccountClient();
        a.Auto_Case_Creation__c = true;
        insert a;
        Contact con = TestUtil.createContact(a.Id);
        insert con;
        
        Booking__c bo = new Booking__c();
		bo.Name = 'test book';
		bo.Account__c = a.Id;
		bo.Order_Contact__c = con.Id;
		bo.Commodity__c = 'SACK';
		bo.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		insert bo;
		
		Test.startTest();
		bo.Booking_Rejected_by_Depot__c = true;
		bo.Reason_for_Depot_Rejection__c = 'reason';
		update bo;
		Test.stopTest();
		
		List<Case> cases = [SELECT Subject, Booking__c, AccountId, ContactId, Description, Origin, Status, Type, Priority FROM Case];
		
		system.assertEquals(1, cases.size());
		system.assertEquals(bo.Id, cases[0].Booking__c);
		system.assertEquals(bo.Account__c, cases[0].AccountId);
		system.assertEquals(bo.Order_Contact__c, cases[0].ContactId);
		system.assertEquals(bo.Reason_for_Depot_Rejection__c, cases[0].Description);
		
     }
     
     static testMethod void testBookingRejectedUpdate() {

        Account a = TestUtil.createAccountClient();
        a.Auto_Case_Creation__c = true;
        insert a;
        
        Account d = TestUtil.createAccountDepot();
        insert d;
        
        Contact con = TestUtil.createContact(a.Id);
        insert con;
        
        Booking__c bo = new Booking__c();
		bo.Name = 'test book';
		bo.Account__c = a.Id;
		bo.Order_Contact__c = con.Id;
		bo.Commodity__c = 'SACK';
		bo.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		insert bo;
		
		
		bo.Booking_Rejected_by_Depot__c = true;
		bo.Reason_for_Depot_Rejection__c = 'reason';
		bo.Collection_Depot__c = d.Id;
		update bo;
		
		Test.startTest();
		update bo;
		Test.stopTest();
		
		List<Case> cases = [SELECT Subject FROM Case];
		
		system.assertEquals(1, cases.size());
     }*/
     
     static testMethod void testUpdateAccountLob()
     {
     	Account a1 = TestUtil.createAccountClient();
     	a1.Name += '1';
     	Account a2 = TestUtil.createAccountClient();
     	a2.Name += '2';
        insert new List<Account>{a1,a2};
        
        Contact con1 = TestUtil.createContact(a1.Id);
        Contact con2 = TestUtil.createContact(a2.Id);
        con2.LastName += 'Second';
        con2.Email += '123';
        insert new List<Contact>{con1,con2};
        
        Line_Of_Business__c lob1 = new Line_Of_Business__c();
		lob1.Name = 'LOB1';
		lob1.Line_Of_Business_Reference__c = '10';
		Line_Of_Business__c lob2 = new Line_Of_Business__c();
		lob2.Name = 'LOB2';
		lob2.Line_Of_Business_Reference__c = '20';
		insert new List<Line_Of_Business__c>{lob1,lob2};
		insert new List<Account_LOB__c>{new Account_LOB__c(Account__c = a1.Id, Line_Of_Business__c = lob1.id), 
										new Account_LOB__c(Account__c = a1.Id, Line_Of_Business__c = lob2.id),
										new Account_LOB__c(Account__c = a2.Id, Line_Of_Business__c = lob2.id)};
        
        Booking__c bo1 = new Booking__c();
		bo1.Name = 'test book1';
		bo1.Account__c = a1.Id;
		bo1.Order_Contact__c = con1.Id;
		bo1.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		bo1.Line_Of_Business__c = lob1.id;
		bo1.Commodity__c = 'SACK';
        Booking__c bo2 = new Booking__c();
		bo2.Name = 'test book2';
		bo2.Account__c = a2.Id;
		bo2.Order_Contact__c = con2.Id;
		bo2.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		bo2.Line_Of_Business__c = lob2.id;
		bo2.Commodity__c = 'SACK';
		insert new List<Booking__c>{bo1,bo2};
		
		Booking__c bo1Old = bo1.clone(true,true);
		Booking__c bo2Old = bo2.clone(true,true);
		bo1.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_COLLECTED;
		bo2.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_COLLECTED;
		
		Date refDate = Date.today();
		
		Test.startTest();
		BookingTriggerHandler.updateAccountLob(new List<Booking__c>{bo1,bo2}, new Map<Id,Booking__c>{bo1.Id => bo1Old,bo2.Id => bo2Old});
		Test.stopTest();
		
		List<Account_LOB__c> als = [select Last_Collection_Date__c from Account_LOB__c 
									order by Account__r.Name asc, Line_Of_Business__r.Name asc];	// order important!!!
		system.assertEquals(3,als.size());
		system.assert(als.get(0).Last_Collection_Date__c >= refDate);	// a1, lob1	- updated
		system.assert(als.get(1).Last_Collection_Date__c == null);		// a1, lob2 - not updated
		system.assert(als.get(2).Last_Collection_Date__c >= refDate);	// a2, lob2 - updated
     }
     
     static testMethod void testBookingIdCreation() {
		Integer stDepot = Integer.valueOf(Label.Salesforce_Start_Depot);
		
		Booking_Id_Settings__c bis = new Booking_Id_Settings__c();
		bis.Name = 'Default';
		bis.Prefix__c = stDepot;
		bis.Current_Number__c = 9999999;
		insert bis;
		
        Account a = TestUtil.createAccountClient();
        insert a;
        Contact con = TestUtil.createContact(a.Id);
        insert con;
        
        Booking__c bo = new Booking__c();
		bo.Name = 'test book';
		bo.Account__c = a.Id;
		bo.Order_Contact__c = con.Id;
		bo.Commodity__c = 'SACK';
		bo.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		insert bo;
		
		bo = [SELECT Booking_Id__c FROM Booking__c WHERE Id = : bo.Id];
		system.assertEquals(Label.Salesforce_Start_Depot+'9999999', bo.Booking_Id__c);
		
		bis = [SELECT Prefix__c, Current_Number__c FROM Booking_Id_Settings__c WHERE Name = 'Default'];
		system.assertEquals(stDepot+1, bis.Prefix__c);
		system.assertEquals(0, bis.Current_Number__c);
     }
     
     static testMethod void testUpdateLastUsedOnAccountAddress()
     {
        Account a = TestUtil.createAccountClient();
        insert a;
        Contact con = TestUtil.createContact(a.Id);
        insert con;
        Account_Address__c aaCol = TestUtil.createAccountAddress(a.Id,null);
        aaCol.Default__c = true;
        Account_Address__c aaDel = TestUtil.createAccountAddress(a.Id,null);
        aaDel.Postcode__c = 'N1 9NL';
        insert new List<Account_Address__c>{aaCol,aaDel};
        Account depot = TestUtil.createAccountDepot();
        insert depot;
        
        Booking__c bo = new Booking__c();
        bo.Name = 'test book';
        bo.Account__c = a.Id;
        bo.Order_Contact__c = con.Id;
        bo.Collection_Contact__c = con.Id;
        bo.Coll_Account_Address__c = aaCol.id;
        bo.Del_Account_Address__c = aaDel.id;
        bo.Collection_Depot__c = depot.id;
        bo.Commodity__c = 'SACK';
        bo.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
        insert bo;
        
        aaCol.Last_Used__c = null;
        aaDel.Last_Used__c = null;
        update new List<Account_Address__c>{aaCol,aaDel};
        
        List<Booking__c> newBookList = new List<Booking__c>{bo.clone(true,true)};
        bo.Coll_Account_Address__c = null;
        bo.Del_Account_Address__c = null;
        Map<Id,Booking__c> oldBookMap = new Map<Id,Booking__c>{bo.id => bo};
        
        Test.startTest();
        BookingTriggerHandler.updateLastUsedOnAccountAddress(newBookList,oldBookMap);
        Test.stopTest();
        system.assertEquals(2,[select count() from Account_Address__c where Last_Used__c != null]);
     }
     
     static testMethod void testBookingRejectionToCS() 
     {
	
         //Added by DH 25/01/2016
        List<RejectionCaseLOBs__c> rjcs = new List<RejectionCaseLOBs__c>();
        rjcs.add(new RejectionCaseLOBs__c(Name = '010'));
        rjcs.add(new RejectionCaseLOBs__c(Name = '251'));
        rjcs.add(new RejectionCaseLOBs__c(Name = '190'));
        rjcs.add(new RejectionCaseLOBs__c(Name = '240'));
        rjcs.add(new RejectionCaseLOBs__c(Name = '160'));
         rjcs.add(new RejectionCaseLOBs__c(Name = '260'));
         rjcs.add(new RejectionCaseLOBs__c(Name = '280'));
         rjcs.add(new RejectionCaseLOBs__c(Name = '370'));
         insert rjcs;
        
         //Create LOBs ***********
         Line_Of_Business__c lobForCase = new Line_Of_Business__c(Line_of_Business_Reference__c = '010');//Will do rejection case creation
         
         insert lobForCase;
         
         Line_Of_Business__c lobForWithoutCase = new Line_Of_Business__c(Line_of_Business_Reference__c = '390');//Will NOT do rejection case creation
         
         insert lobForWithoutCase;
         //***********************
         
        Account a = TestUtil.createAccountClient();
        a.Auto_Case_Creation__c = true;
        a.Collection_Queue__c = 'Lount_Admin_1';
        insert a;
        Account depot = TestUtil.createAccountDepot();
        insert depot;
        Contact con = TestUtil.createContact(a.Id);
        insert con;
               
        Booking__c bo = new Booking__c();
		bo.Name = 'test book';
		bo.Account__c = a.Id;
		bo.Order_Contact__c = con.Id;
		bo.Commodity__c = 'SACK';
		bo.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		bo.Collection_Depot__c = depot.Id;
         
        Account b = TestUtil.createAccountClient();
        b.Auto_Case_Creation__c = true;
        b.Collection_Queue__c = 'Lount_Admin_1';
        insert b;
        Contact con2 = TestUtil.createContact(b.Id);
        insert con2;
         
                     
        Booking__c boLOBNoCase = new Booking__c();
		boLOBNoCase.Name = 'test book2';
		boLOBNoCase.Account__c = b.Id;
		boLOBNoCase.Order_Contact__c = con2.Id;
		boLOBNoCase.Commodity__c = 'SACK';
		boLOBNoCase.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		boLOBNoCase.Collection_Depot__c = depot.Id;
         
        Account c = TestUtil.createAccountClient();
        c.Auto_Case_Creation__c = false;//Should not create a case even if LOB is in custom list
        c.Major_Account__c = true;
        c.Collection_Queue__c = 'Lount_Admin_1';
        insert c;
        Contact con3 = TestUtil.createContact(c.Id);
        insert con3;
        
        Booking__c boNotAutoCase = new Booking__c();
		boNotAutoCase.Name = 'test book3';
		boNotAutoCase.Account__c = c.Id;
		boNotAutoCase.Order_Contact__c = con3.Id;
		boNotAutoCase.Commodity__c = 'SACK';
		boNotAutoCase.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		boNotAutoCase.Collection_Depot__c = depot.Id;
        
        Booking__c boNoAccount = new Booking__c();
		boNoAccount.Name = 'test book4';
		//boNotAutoCase.Account__c = c.Id;
		//boNotAutoCase.Order_Contact__c = con3.Id;
		boNoAccount.Commodity__c = 'SACK';
		boNoAccount.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		boNoAccount.Collection_Depot__c = depot.Id;
        
         bo.Line_of_Business__c = lobForCase.id;
         boLOBNoCase.Line_of_Business__c = lobForWithoutCase.id;    
         boNotAutoCase.Line_of_Business__c = lobForCase.id;//In list but should be created as AutoCase not selected
	     
         insert bo;
         insert boLOBNoCase;
         insert boNotAutoCase;
         insert boNoAccount;
         
         system.assert(ConstantUtil.AutoRejectionCaseLOBList.size() == 8);
         Set<string> testLOB = ConstantUtil.AutoRejectionCaseLOBList;
         for(string s:testLOB)
         {
             system.debug('**Code: ' + s);
         }
         
		Test.startTest();
		bo.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_REJECTED_TO_CS;
        boLOBNoCase.Status__c =  ConstantUtil.PLVAL_BOOKING_STATUS_REJECTED_TO_CS;
        boNotAutoCase.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_REJECTED_TO_CS;
        boNoAccount.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_REJECTED_TO_CS;
		update bo;
        update boLOBNoCase;
        update boNotAutoCase;
        update boNoAccount;
        Test.stopTest();
		
		//Only 1 Case should be created for the bookings whos LOB code matches the custom list RejectionCaseLOBs and has AutoCase selected on Account
      
		List<Case> cases = [SELECT Subject, Booking__c, AccountId, ContactId, Description, Origin, Status, Type, Priority, OwnerId FROM Case order by createdDate];
		
        //Assert that only 2 cases created out of the 4 bookings and that they are the expected as ordered by creation datetime
        system.assertEquals(2, cases.size());
         
		system.assertEquals(bo.Id, cases[0].Booking__c);
		system.assertEquals(bo.Account__c, cases[0].AccountId);
		system.assertEquals(bo.Order_Contact__c, cases[0].ContactId);
		system.assertEquals(ConstantUtil.PLVAL_CASE_ORIGIN_SYSTEM, cases[0].Origin);
		system.assertEquals(ConstantUtil.LOUNT_ADMIN_1_QUEUE_ID, cases[0].OwnerId);
         
        system.assertEquals(boNoAccount.Id, cases[1].Booking__c);
		system.assertEquals(ConstantUtil.PLVAL_CASE_ORIGIN_SYSTEM, cases[1].Origin);
        system.debug(cases[1].OwnerId);
        Group g = [Select id from Group where Name = 'Unassigned' limit 1];
		system.assertEquals(g.id , cases[1].OwnerId);
         
	
		
     }

     static testMethod void testBookingLocking() {

        Account a = TestUtil.createAccountClient();
        insert a;
        Contact con = TestUtil.createContact(a.Id);
        insert con;
        
        Booking__c bo = new Booking__c();
		bo.Name = 'test book';
		bo.Account__c = a.Id;
		bo.Order_Contact__c = con.Id;
		bo.Commodity__c = 'SACK';
		bo.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		insert bo;

		bo = [SELECT Id, RecordType.Name FROM Booking__c WHERE Id = :bo.Id];
		System.assertEquals(ConstantUtil.PLVAL_BOOKING_RECORD_TYPE_NEW,bo.RecordType.Name);
		
		Test.startTest();

		bo.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_COLLECTED;
		update bo;

		bo = [SELECT Id, RecordType.Name FROM Booking__c WHERE Id = :bo.Id];
		System.assertEquals(ConstantUtil.PLVAL_BOOKING_RECORD_TYPE_BLOCKED,bo.RecordType.Name);

		Test.stopTest();
		
     }

     static testMethod void testBookingUnlocking() {

        Account a = TestUtil.createAccountClient();
        insert a;
        Contact con = TestUtil.createContact(a.Id);
        insert con;
        
        Booking__c bo = new Booking__c();
		bo.Name = 'test book';
		bo.Account__c = a.Id;
		bo.Order_Contact__c = con.Id;
		bo.Commodity__c = 'SACK';
		bo.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_COLLECTED;
		insert bo;

		bo = [SELECT Id, RecordType.Name FROM Booking__c WHERE Id = :bo.Id];
		System.assertEquals(ConstantUtil.PLVAL_BOOKING_RECORD_TYPE_BLOCKED,bo.RecordType.Name);
		
		Test.startTest();

		bo.Status__c = ConstantUtil.PLVAL_BOOKING_STATUS_CONFIRMED;
		update bo;

		bo = [SELECT Id, RecordType.Name FROM Booking__c WHERE Id = :bo.Id];
		System.assertEquals(ConstantUtil.PLVAL_BOOKING_RECORD_TYPE_NEW,bo.RecordType.Name);

		Test.stopTest();
		
     }
}