objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments_on_account_address__c</fullName>
        <description>Text field to add any comments on the account address during a booking</description>
        <inlineHelpText>Are there any additional comments that the customer has made about the account address?</inlineHelpText>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County/Region</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Used__c</fullName>
        <label>Last Used</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legacy_Address_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Address Id (Legacy)</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Org_Name__c</fullName>
        <label>Org Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Premise_Name__c</fullName>
        <label>Premise Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <label>Street Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Account Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Postcode__c.object
<CustomObject>
    <fields>
        <fullName>Postcode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Postcode</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Postcode</label>
    <nameField>
        <label>Postcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DefaultAccount.cls
public with sharing class DefaultAccount {

    private final Account acct;
    public Account_Address__c defAdd {get; set;}
    public boolean isDefault {get; set;}
    
    public DefaultAccount(ApexPages.StandardController controller) {
        this.acct = (Account)controller.getRecord();
        try{
            defAdd = [Select Legacy_Address_Id__c,Org_Name__c,Premise_Name__c,Street_1__c,Street_2__c,City__c,District__c,County__c,Postcode__c,Contact__c,Last_Used__c,Comments_on_account_address__c
                        from Account_Address__c where Account__c =: acct.Id and Default__c =: true limit 1];
            isDefault = true;
        }
        catch(exception e) {
            isDefault = false;
        }
    }
}