objects/Account.object
<CustomObject>
    <fields>
        <fullName>On_Stop__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When this field is checked, the Account is ON STOP. Only a Stubbins user is able to edit the status of an Account which is ON STOP.</description>
        <inlineHelpText>When this field is checked, the Account is ON STOP. Only a Stubbins user is able to edit the status of an Account which is ON STOP.</inlineHelpText>
        <label>On Stop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Stubbins_Permission__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request Stubbins Permission</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stubbins_Temporary_Permission__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to allow activities with an account that is on stop for a few hours</description>
        <label>Stubbins Temporary Permission</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OL_AccountOnStopSubmitTest.cls
/**
* File Name   :    OL_AccountOnStopSubmitTest.cls
* Description :    
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 05/08/2014 Klea Kolaric	Initial version
*
*/
@isTest
public class OL_AccountOnStopSubmitTest {
	
	public static testMethod void testNotOnStop()
	{
		Account a = TestUtil.createAccountClient();
		a.On_Stop__c = false;
		insert a;
		
		Test.setCurrentPage(Page.OL_AccountOnStopSubmitAgent);
		Apexpages.currentPage().getParameters().put('id',a.id);
		
		Test.startTest();
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(a);
		OL_AccountOnStopSubmit aoss = new OL_AccountOnStopSubmit(sc);
		aoss.submitAccount();
		Test.stopTest();
	}
	
	public static testMethod void testHasTmpPermission()
	{
		Account a = TestUtil.createAccountClient();
		a.On_Stop__c = true;
		a.Request_Stubbins_Permission__c = true;
		a.Stubbins_Temporary_Permission__c = true;
		insert a;
		
		Test.setCurrentPage(Page.OL_AccountOnStopSubmitAgent);
		Apexpages.currentPage().getParameters().put('id',a.id);
		
		Test.startTest();
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(a);
		OL_AccountOnStopSubmit aoss = new OL_AccountOnStopSubmit(sc);
		aoss.submitAccount();
		Test.stopTest();
	}
	
	public static testMethod void testOnStop()
	{
		Account a = TestUtil.createAccountClient();
		a.On_Stop__c = true;
		insert a;
		
		Test.setCurrentPage(Page.OL_AccountOnStopSubmitAgent);
		Apexpages.currentPage().getParameters().put('id',a.id);
		
		Test.startTest();
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(a);
		OL_AccountOnStopSubmit aoss = new OL_AccountOnStopSubmit(sc);
		aoss.submitAccount();
		// try again to catch error
		aoss.submitAccount();
		Test.stopTest();
	}

}