objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auto_Case_Creation__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If Checked then cases are auto created for this account if any associated bookings are &apos;Rejected to Customer Services&apos;. 

The box is automatically Unchecked when an Account becomes a Major Account and vice versa.</description>
        <inlineHelpText>If Checked then cases are auto created for this account if any associated bookings are &apos;Rejected to Customer Services&apos;. 

The box is automatically Unchecked when an Account becomes a Major Account and vice versa.</inlineHelpText>
        <label>Auto Case Creation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses (Collection Depot)</relationshipLabel>
        <relationshipName>Account_Addresses2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Depot</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses (Delivery Depot)</relationshipLabel>
        <relationshipName>Account_Addresses3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Account Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account_LOB__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account LOBs</relationshipLabel>
        <relationshipName>Account_LOBs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Line of Business</label>
        <referenceTo>Line_of_Business__c</referenceTo>
        <relationshipLabel>Account LOBs</relationshipLabel>
        <relationshipName>Account_LOBs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account LOB</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Account LOB Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account LOBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Booking_Rejected_by_Depot__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is checked when a depot rejects a booking. A reason for this rejection should be provided as a text comment with the rejection.</description>
        <label>Booking Rejected by Depot</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Auto populated by routing table logic</description>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Collection Depot must be an Account of type &quot;Depot&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <filterItems>
                <field>Account.Operational_for_Bookings__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings (Collection Depot)</relationshipLabel>
        <relationshipName>ColDepBookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Auto populated by routing table logic</description>
        <label>Delivery Depot</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Delivery Depot must be an Account of type &quot;Depot&quot;.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings (Delivery Depot)</relationshipLabel>
        <relationshipName>DelDepBookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Restricted by Line of Buisness on Account (Account_LOB__c)</description>
        <label>Line of Business (Division)</label>
        <referenceTo>Line_of_Business__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Depot_Rejection__c</fullName>
        <description>When a depot rejects a booking, they need to check the &apos;Booking Rejected by Depot&apos; field, which will raise a case. A reason for this rejection should be provided as a text comment with the rejection.</description>
        <inlineHelpText>What is the reason for the Depot rejecting the booking?</inlineHelpText>
        <label>Reason for Depot Rejection</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Confirmed</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Not Collected</fullName>
                <color>#FF6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated to Round</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
                <color>#000000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#BBBBBB</color>
            </picklistValues>
            <picklistValues>
                <fullName>Collected</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected to Customer Services</fullName>
                <color>#FF0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup field to a Booking so that case can be related to a specific booking e.g. for failed collections</description>
        <inlineHelpText>Is this case related to a Booking?</inlineHelpText>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Types_Level_2__c</fullName>
        <label>Sub Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Check Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C.I.T Query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice Query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redelivery Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stationary Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transit Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paperwork Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return to Sender</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accessibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreement not Met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damaged Consignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Collection_Depot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If a Collection Exception is selected then the Case will be assigned using the &apos;Collection Queue&apos; field for this Depot. 

Click on the Depot to see where this case would be assigned to.</inlineHelpText>
        <label>Collection Depot</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select an account of type &apos;Depot&apos;.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Collection Depot)</relationshipLabel>
        <relationshipName>CollectionCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proactive_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <description>By default, any case which results from a customer contacting TNT first is Reactive. Checking this field indicates that a Proactive Case has been raised on behalf of the customer, before the customer has contacted TNT.</description>
        <inlineHelpText>By default, any case which results from a customer contacting TNT first is Reactive. Checking this field indicates that a Proactive Case has been raised on behalf of the customer, before the customer has contacted TNT.</inlineHelpText>
        <label>Proactive Case</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Line_of_Business__c.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business_Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique reference for the line of Business.</description>
        <externalId>true</externalId>
        <label>Line of Business Reference</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Line of Business</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines of Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BookingTriggerHandler.cls
/**
* File Name   :    BookingTriggerHandler.cls
* Description :    methods called from Booking trigger
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 24/07/2014 Liza Romanenko	Initial version TNT-536
* 0.2 28/08/2014 Klea Kolaric	TNT-1400
* 0.3 29/08/2014 Liza Romanenko add generateBookingId() method TNT-1414
* 0.4 12/09/2014 Liza Romanenko update createCaseIfRejected() method TNT-1605
*
*/
public with sharing class BookingTriggerHandler {
	
	// HANDLERS
	
	public static void onBeforeInsertHandler(List<Booking__c> triggerNew)
	{
		generateBookingId(triggerNew);
		maintainRecordType(triggerNew);
	}
	
	public static void onAfterInsertHandler(List<Booking__c> triggerNew)
	{
		updateAccountLob(triggerNew,null);
		updateLastUsedOnAccountAddress(triggerNew,null);
	}
	
	public static void onAfterUpdateHandler(List<Booking__c> triggerNew, Map<Id,Booking__c> triggerOldMap)
	{
		createCaseIfRejected(triggerNew, triggerOldMap);
		updateAccountLob(triggerNew, triggerOldMap);
		updateLastUsedOnAccountAddress(triggerNew,triggerOldMap);
	}

	public static void onBeforeUpdateHandler(List<Booking__c> triggerNew, Map<Id,Booking__c> triggerOldMap)
	{
		maintainRecordType(triggerNew);
	}
	
	// METHODS
	
	public static void createCaseIfRejected(List<Booking__c> bookings, Map<Id,Booking__c> oldMap){
		
		List<Booking__c> books = new List<Booking__c>();
		for(Booking__c b : bookings)
		{
			if( (b.Booking_Rejected_by_Depot__c && (b.Booking_Rejected_by_Depot__c != oldMap.get(b.Id).Booking_Rejected_by_Depot__c))
				|| (b.Status__c == ConstantUtil.PLVAL_BOOKING_STATUS_REJECTED_TO_CS && (b.Status__c != oldMap.get(b.Id).Status__c)) )
			{
				books.add(b);
			}
		}
		if(books.isEmpty()) return;
		
        System.debug('Bookings Not Empty');
        
		// find all relevant accounts
		Map<Id,Account> accMap = new Map<Id,Account>();
		{
			Set<Id> accIds = new Set<Id>();
			for(Booking__c b : books)
			{
				if(b.Account__c != null)
				{
					accIds.add(b.Account__c);
				}
			}
			if(!accIds.isEmpty())
			{
				accMap = new Map<Id,Account>([select id, Auto_Case_Creation__c from Account where id in :accIds]);
			}
		}
        
        // find all relevant LOBs added by DH 22/01/2016
        Map<Id,Line_Of_Business__c> lobMap = new Map<Id,Line_Of_Business__c>();
		{
			Set<Id> lobIds = new Set<Id>();
			for(Booking__c b : books)
			{
				if(b.Line_Of_Business__c != null)
				{
					lobIds.add(b.Line_Of_Business__c);
				}
			}
			if(!lobIds.isEmpty())
			{
				lobMap = new Map<Id,Line_Of_Business__c>([select id, Line_Of_Business_Reference__c from Line_Of_Business__c where id in :lobIds]);
			}
		}
		
        
             
		List<Case> cases = new List<Case>();
        
        Set<String> AutoCaseLOBs = ConstantUtil.AutoRejectionCaseLOBList;
        
        
		for(Booking__c b : books){
           
            System.Debug('This bookings LOB is: ' + b.Line_of_Business__c);
            
			if(b.Account__c == null || (accMap.get(b.Account__c).Auto_Case_Creation__c && (lobMap.containsKey(b.Line_of_Business__c) && AutoCaseLOBs.contains(lobMap.get(b.Line_of_Business__c).Line_of_Business_Reference__c))))
			{
				//check if rejected
				/*Change made by Liza Romanenko
				Code depricated, had a discussion with Kishan he said this is not used 9 Apr 2015	
				if(b.Booking_Rejected_by_Depot__c && (b.Booking_Rejected_by_Depot__c != oldMap.get(b.Id).Booking_Rejected_by_Depot__c)){
					//Create Case
					Case c = createCase(b);
					c.Subject = 'Booking ' + b.Name + ' Rejected';
					c.Description = b.Reason_for_Depot_Rejection__c;
					c.Origin = ConstantUtil.PLVAL_CASE_ORIGIN_PHONE;
					c.Type = ConstantUtil.PLVAL_CASE_TYPE_BOOKING_ADN_QUOTES;
					
					cases.add(c);
				} */
                               
				if(b.Status__c == ConstantUtil.PLVAL_BOOKING_STATUS_REJECTED_TO_CS && (b.Status__c != oldMap.get(b.Id).Status__c)){
					//Create Case
					Case c = createCase(b);
					c.Subject = 'Booking ' + b.Name + ' Rejected to CS';
					c.Description = b.Reason_for_Depot_Rejection__c;
					c.Origin = ConstantUtil.PLVAL_CASE_ORIGIN_SYSTEM;
					c.Type = ConstantUtil.PLVAL_CASE_TYPE_BOOKINGS;
					c.Case_Types_Level_2__c = ConstantUtil.PLVAL_CASE_TYPE_LAVEL1_CS_FAILED_COLLECTION;
					c.Proactive_Case__c = true;
					c.Collection_Depot__c = b.Collection_Depot__c;
					c.Delivery_Depot__c = b.Delivery_Depot__c;
					c.Exception__c = ConstantUtil.PLVAL_CASE_EXCEPTION_COLLECTION;
                    //DH added 01/02/2016 for call back
                    c.Call_me_back__c = '1 hour';
                    
					cases.add(c);
				}
			}
		}
		
		if(!cases.isEmpty()){
			// make sure cases pass through assignment rule
			AssignmentRule AR = [select id from AssignmentRule where SobjectType = 'Case' and Active = true limit 1];
			//Creating the DMLOptions for "Assign using active assignment rules" checkbox
			Database.DMLOptions dmlOpts = new Database.DMLOptions();
			dmlOpts.assignmentRuleHeader.assignmentRuleId = AR.id;
			for(Case c : cases) {
				c.setOptions(dmlOpts);
			}
			
			insert cases;
		}
	}
	
	private static Case createCase(Booking__c b){
		Case c = new Case();
		c.AccountId = b.Account__c;
		c.Booking__c = b.Id;
		c.ContactId = b.Order_Contact__c;
		c.Status = ConstantUtil.PLVAL_CASE_STATUS_NEW;
		c.Priority = ConstantUtil.PLVAL_CASE_PRIORITY_MEDIUM;
		return c;
	}	

	public static void updateAccountLob(List<Booking__c> triggerNew, Map<Id,Booking__c> triggerOldMap)
	{
		final String US = '_';
		Boolean isInsert = triggerOldMap == null;
		Set<String> bookCombo = new Set<String>();	// accountID_lineOfBusinessID
		Set<id> accIds = new Set<id>();
		Set<id> lobIds = new Set<id>();
		
		for(Booking__c bo: triggerNew)
		{
			if(bo.Status__c == ConstantUtil.PLVAL_BOOKING_STATUS_COLLECTED && bo.Account__c != null && bo.Line_Of_Business__c != null
				&& (isInsert || triggerOldMap.get(bo.id).Status__c != ConstantUtil.PLVAL_BOOKING_STATUS_COLLECTED))
			{
				accIds.add(bo.Account__c);
				lobIds.add(bo.Line_Of_Business__c);
				bookCombo.add(bo.Account__c+US+bo.Line_Of_Business__c);
			}
		}
		
		if(!bookCombo.isEmpty()) {
			List<Account_LOB__c> acclobs = [SELECT ID, Last_Collection_Date__c, Account__c, 
												   Line_Of_Business__c
											  FROM Account_LOB__c
											 WHERE Account__c IN :accIds
													AND Line_Of_Business__c IN :lobIds
												    AND (Last_Collection_Date__c < TODAY OR Last_Collection_Date__c = null)];
			
			Integer n = acclobs.size();							
			for(Integer i = 0; i < n; i++)
			{
				Account_LOB__c al = acclobs.get(i);
				if(bookCombo.contains(al.Account__c+US+al.Line_Of_Business__c))
				{
					al.Last_Collection_Date__c = Date.today();
				}
				else
				{
					acclobs.remove(i);
					i--;
					n--;
				}
			}
			update acclobs;
		}
	}
	
	public static void generateBookingId(List<Booking__c> bookings){
		
        Boolean generateIds = false;

        for(Booking__c bk : bookings) {
            if(bk.Booking_Id__c == null) {
                generateIds = true;
                break;
            }
        }

        if(generateIds) {

            Integer startDepot = Integer.valueOf(Label.Salesforce_Start_Depot);
            Integer endDepot = Integer.valueOf(Label.Salesforce_End_Depot);

            list<Booking_Id_Settings__c> biss = [SELECT Prefix__c, Current_Number__c FROM Booking_Id_Settings__c WHERE Name = 'Default' FOR UPDATE];

            if(biss.isEmpty()) {
                biss.add(new Booking_Id_Settings__c(Name = 'Default', Prefix__c = Integer.valueOf(Label.Salesforce_Start_Depot), Current_Number__c = 0));
            }

            Booking_Id_Settings__c bis = biss.get(0);

            Integer prefix = (Integer)bis.Prefix__c;
            Integer numPointer = (Integer)bis.Current_Number__c;

            for(Booking__c bk : bookings) {
                if(bk.Booking_Id__c == null) {

                    bk.Booking_Id__c = String.valueOf((prefix*10000000) + numPointer);
                    //increment number and prefix
                    numPointer++;
                    if(numPointer == 10000000){
                        numPointer = 0;
                        prefix = prefix == endDepot ? startDepot : prefix + 1;
                    }
                }
            }

            bis.Prefix__c = prefix;
            bis.Current_Number__c = numPointer;
            
            upsert bis;
        }

        for(Booking__c bk : bookings) {
            if(bk.Name == null || bk.Name == '') {
                bk.Name = bk.Booking_Id__c;
            }
        }
	}
	
	public static void updateLastUsedOnAccountAddress(List<Booking__c> triggerNew, Map<Id,Booking__c> triggerOldMap)
	{
		Set<Id> aaIds = new Set<Id>();
		for(Booking__c book : triggerNew)
		{
			if(book.Coll_Account_Address__c != null 
				&& (triggerOldMap == null || book.Coll_Account_Address__c != triggerOldMap.get(book.id).Coll_Account_Address__c))
			{
				aaIds.add(book.Coll_Account_Address__c);
			}
			if(book.Del_Account_Address__c != null
				&& (triggerOldMap == null || book.Del_Account_Address__c != triggerOldMap.get(book.id).Del_Account_Address__c))
			{
				aaIds.add(book.Del_Account_Address__c);
			}
		}
		
		if(!aaIds.isEmpty())
		{
			List<Account_Address__c> aas = [select id, Last_Used__c from Account_Address__c where id in :aaIds];
			for(Account_Address__c aa : aas)
			{
				aa.Last_Used__c = Datetime.now();
			}
			update aas;
		}
	}

	private static void maintainRecordType(List<Booking__c> triggerNew) {
/*
		Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Booking__c.RecordTypeInfosByName;
		Id newBookingId = rtMapByName.get(ConstantUtil.PLVAL_BOOKING_RECORD_TYPE_NEW).RecordTypeId;
		Id blockedBookingId = rtMapByName.get(ConstantUtil.PLVAL_BOOKING_RECORD_TYPE_BLOCKED).RecordTypeId;

		for(Booking__c book : triggerNew) {
			if((book.Status__c == ConstantUtil.PLVAL_BOOKING_STATUS_COLLECTED || book.Status__c == ConstantUtil.PLVAL_BOOKING_STATUS_CANCELLED)
				&& book.RecordTypeId != blockedBookingId) {
                System.debug('****I am setting this booking to a BLOCKED booking Record type****');
				book.RecordTypeId = blockedBookingId;
			}
			else if(book.RecordTypeId != newBookingId) {
				System.debug('****I am setting this booking to a NEW booking Record type****');
                book.RecordTypeId = newBookingId;
			}
		}
*/	}
}