objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Account Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CS_Claims__c.object
<CustomObject>
    <description>TNT UK Claims Form Attachment Handling SR 2751</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Depot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Depot</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Depot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Claims (Depot)</relationshipLabel>
        <relationshipName>DepotClaims</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Depot_no__c</fullName>
        <inlineHelpText>Is auto populated from the Depot field when clicking &apos;Save&apos;.</inlineHelpText>
        <label>Depot no</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Contact_Name__c</fullName>
        <label>Contact name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNT_account_no__c</fullName>
        <inlineHelpText>Is auto populated from the Account field when clicking &apos;Save&apos;.</inlineHelpText>
        <label>TNT account no</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>Claim Form</label>
    <nameField>
        <displayFormat>CLN-{000000}</displayFormat>
        <label>Claim Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CS_ClaimsTriggerHandlerTest.cls
/**
* File Name   :    CS_ClaimsTriggerHandlerTest.cls
* Description :    Test class for CS_ClaimsTriggerHandler.cls
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 17/07/2014 Liza Romanenko	Initial version
*
*
*/
@isTest
private class CS_ClaimsTriggerHandlerTest {

    static testMethod void testFillFieldsFromAccountContactDepot() {
        
        Account a = TestUtil.createAccountClient();
    	insert a;
    	Account d = TestUtil.createAccountDepot();
    	insert d;
    	Contact con = TestUtil.createContact(a.Id);
    	insert con;
    	Account_Address__c aaDef = TestUtil.createAccountAddress(a.Id,null);
    	aaDef.Default__c = true;
    	insert aaDef;
        
        CS_Claims__c claim = new CS_Claims__c();
        claim.Account__c = a.Id;
        claim.Depot__c = d.Id;
        claim.Contact__c = con.Id;
        insert claim;
        
        claim = [SELECT Sender_Contact_Name__c, TNT_account_no__c, Depot_no__c FROM CS_Claims__c WHERE Id = : claim.Id];
        
        system.assertEquals(claim.Sender_Contact_Name__c, 'Test Class Contact');
        system.assertEquals(claim.TNT_account_no__c, '111');
        system.assertEquals(claim.Depot_no__c, '222');
    }
}