objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Depot</fullName>
        <active>true</active>
        <description>Account for TNT Depots</description>
        <label>Depot</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City/Town</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Account Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Day__c.object
<CustomObject>
    <fields>
        <fullName>Day_Type__c</fullName>
        <label>Day Type</label>
        <picklist>
            <picklistValues>
                <fullName>Working Day</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Working Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Day</label>
    <nameField>
        <label>Date</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Depot_Routing__c.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Division number – as an override- or blank for all divisions</description>
        <inlineHelpText>Division number – as an override- or blank for all divisions</inlineHelpText>
        <label>Line of Business</label>
        <referenceTo>Line_of_Business__c</referenceTo>
        <relationshipLabel>Depot Routings</relationshipLabel>
        <relationshipName>Depot_Routings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Round_Group__c</fullName>
        <label>Round Group</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Routing_Network__c</fullName>
        <label>Routing Network</label>
        <picklist>
            <picklistValues>
                <fullName>EXP</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EWW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RET</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Routing_Table__c</fullName>
        <label>Routing Table</label>
        <referenceTo>Routing_Table__c</referenceTo>
        <relationshipLabel>Depot Routings</relationshipLabel>
        <relationshipName>Depot_Routings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Depot Routing</label>
    <nameField>
        <displayFormat>DR-{00000000}</displayFormat>
        <label>Depot Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Routings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Line_of_Business__c.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business_Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique reference for the line of Business.</description>
        <externalId>true</externalId>
        <label>Line of Business Reference</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Routing_Network__c</fullName>
        <description>Type of routing network that the consignment will use. Certain goods must be handled by a specialist network of depots (e.g. Fashion).</description>
        <label>Routing Network</label>
        <picklist>
            <picklistValues>
                <fullName>EWW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RET</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Line of Business</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines of Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Postcode__c.object
<CustomObject>
    <fields>
        <fullName>Postcode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Postcode</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Postcode</label>
    <nameField>
        <label>Postcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Routing_Table__c.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <externalId>true</externalId>
        <label>District</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing_Table__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Routing Table Reference</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Routing Table</label>
    <nameField>
        <displayFormat>RT-{00000000}</displayFormat>
        <label>Routing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OL_DepotRoutingHelperTest.cls
/**
* File Name   :    OL_DepotRoutingHelperTest.cls
* Description :    
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 04/09/2014 Klea Kolaric	
*/
@isTest
public class OL_DepotRoutingHelperTest {

    static testMethod void findNormalDepotForWorkingDay()
    {
    	Line_Of_Business__c lob = new Line_Of_Business__c();
		lob.Name = 'LOB1';
		lob.Line_Of_Business_Reference__c = '10';
		lob.Routing_Network__c = 'EXP';
		insert lob;
		Account_Address__c aa = TestUtil.createAccountAddress(null,null);
		Date collDate = Date.newInstance(2014,9,1);	// Monday
		
    	Account depot = TestUtil.setupDepotRouting(lob.id,aa,collDate);

    	Test.startTest();
    	system.assertEquals(depot.id,OL_DepotRoutingHelper.findCollectionDepot(aa.Postcode__c,aa.District__c,aa.City__c,lob.id,collDate).id);
    	Test.stopTest();
    }
    
    static testMethod void findSaturdayDepotForSaturdayDay()
    {
    	Line_Of_Business__c lob = new Line_Of_Business__c();
		lob.Name = 'LOB1';
		lob.Line_Of_Business_Reference__c = '10';
		lob.Routing_Network__c = 'EXP';
		insert lob;
		Account_Address__c aa = TestUtil.createAccountAddress(null,null);
		Date collDate = Date.newInstance(2014,8,30);	// Saturday
		
    	Account depot = TestUtil.setupDepotRouting(lob.id,aa,collDate);
    	
    	// set saturday
    	Day__c d = [select id, Day_Type__c from Day__c limit 1];
		d.Day_Type__c = ConstantUtil.PLVAL_DAY_DAYTYPE_SATURDAY;
		update d;
		Depot_Routing__c dr = [select id, Round_Group__c from Depot_Routing__c limit 1];
		dr.Round_Group__c = ConstantUtil.PLVAL_DEPOTROUTING_ROUNDGROUP_SATURDAY;
		update dr;

    	Test.startTest();
    	system.assertEquals(depot.id,OL_DepotRoutingHelper.findCollectionDepot(aa.Postcode__c,aa.District__c,aa.City__c,lob.id,collDate).id);
    	Test.stopTest();
    }
    
    static testMethod void nonWorkingDay()
    {
    	Line_Of_Business__c lob = new Line_Of_Business__c();
		lob.Name = 'LOB1';
		lob.Line_Of_Business_Reference__c = '10';
		lob.Routing_Network__c = 'EXP';
		insert lob;
		Account_Address__c aa = TestUtil.createAccountAddress(null,null);
		Date collDate = Date.newInstance(2014,8,31);	// Sunday
		
    	Account depot = TestUtil.setupDepotRouting(lob.id,aa,collDate);
    	
    	// set sunday
    	Day__c d = [select id, Day_Type__c from Day__c limit 1];
		d.Day_Type__c = ConstantUtil.PLVAL_DAY_DAYTYPE_NONWORKING;
		update d;
		Depot_Routing__c dr = [select id, Round_Group__c from Depot_Routing__c limit 1];
		dr.Round_Group__c = ConstantUtil.PLVAL_DEPOTROUTING_ROUNDGROUP_ALL;
		update dr;

    	Test.startTest();
    	system.assertEquals(null,OL_DepotRoutingHelper.findCollectionDepot(aa.Postcode__c,aa.District__c,aa.City__c,lob.id,collDate));
    	system.assertNotEquals(null,OL_DepotRoutingHelper.errorMsg);
    	Test.stopTest();
    }
    
    static testMethod void failSaturdayDepotForWorkingDay()
    {
    	Line_Of_Business__c lob = new Line_Of_Business__c();
		lob.Name = 'LOB1';
		lob.Line_Of_Business_Reference__c = '10';
		lob.Routing_Network__c = 'EXP';
		insert lob;
		Account_Address__c aa = TestUtil.createAccountAddress(null,null);
		Date collDate = Date.newInstance(2014,9,1);	// Monday
		
    	Account depot = TestUtil.setupDepotRouting(lob.id,aa,collDate);
    	
		Depot_Routing__c dr = [select id, Round_Group__c from Depot_Routing__c limit 1];
		dr.Round_Group__c = ConstantUtil.PLVAL_DEPOTROUTING_ROUNDGROUP_SATURDAY;
		update dr;

    	Test.startTest();
    	system.assertEquals(null,OL_DepotRoutingHelper.findCollectionDepot(aa.Postcode__c,aa.District__c,aa.City__c,lob.id,collDate));
    	system.assertNotEquals(null,OL_DepotRoutingHelper.errorMsg);
    	Test.stopTest();
    }
    
    static testMethod void failNormalDepotForSaturdayDay()
    {
    	Line_Of_Business__c lob = new Line_Of_Business__c();
		lob.Name = 'LOB1';
		lob.Line_Of_Business_Reference__c = '10';
		lob.Routing_Network__c = 'EXP';
		insert lob;
		Account_Address__c aa = TestUtil.createAccountAddress(null,null);
		Date collDate = Date.newInstance(2014,8,30);	// Saturday
		
    	Account depot = TestUtil.setupDepotRouting(lob.id,aa,collDate);
    	
    	// set saturday
    	Day__c d = [select id, Day_Type__c from Day__c limit 1];
		d.Day_Type__c = ConstantUtil.PLVAL_DAY_DAYTYPE_SATURDAY;
		update d;

    	Test.startTest();
    	system.assertEquals(null,OL_DepotRoutingHelper.findCollectionDepot(aa.Postcode__c,aa.District__c,aa.City__c,lob.id,collDate));
    	system.assertNotEquals(null,OL_DepotRoutingHelper.errorMsg);
    	Test.stopTest();
    }
    
    static testMethod void allFail()
    {
    	Line_Of_Business__c lob = new Line_Of_Business__c();
		lob.Name = 'LOB1';
		lob.Line_Of_Business_Reference__c = '10';
		lob.Routing_Network__c = 'EXP';
		insert lob;
		Account_Address__c aa = TestUtil.createAccountAddress(null,null);
		Date collDate = Date.newInstance(2014,9,1);	// Monday
		
    	Account depot = TestUtil.setupDepotRouting(lob.id,aa,collDate);
    	
    	Test.startTest();
    	system.assertEquals(null,OL_DepotRoutingHelper.findCollectionDepot(null,null,null,null,null));
    	system.assertNotEquals(null,OL_DepotRoutingHelper.errorMsg);
    	delete [select id from Depot_Routing__c];
    	system.assertEquals(null,OL_DepotRoutingHelper.findCollectionDepot(aa.Postcode__c,aa.District__c,aa.City__c,lob.id,collDate));
    	system.assertNotEquals(null,OL_DepotRoutingHelper.errorMsg);
    	delete [select id from Day__c];
    	system.assertEquals(null,OL_DepotRoutingHelper.findCollectionDepot(aa.Postcode__c,aa.District__c,aa.City__c,lob.id,collDate));
    	system.assertNotEquals(null,OL_DepotRoutingHelper.errorMsg);
    	delete [select id from Routing_Table__c];
    	system.assertEquals(null,OL_DepotRoutingHelper.findCollectionDepot(aa.Postcode__c,aa.District__c,aa.City__c,lob.id,collDate));
    	system.assertNotEquals(null,OL_DepotRoutingHelper.errorMsg);
    	Test.stopTest();
    }
}