objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dangerous_Goods__c</fullName>
        <description>does a customer ship dangerous goods?</description>
        <label>Ships Dangerous Goods</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Account Address Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Carriage_Forward__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Carriage Forward</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Coll_Postcode__c</fullName>
        <description>PCOD from GB Mailer</description>
        <label>Collection Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Phone__c</fullName>
        <label>Company Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Dangerous_Goods__c</fullName>
        <defaultValue>false</defaultValue>
        <description>is this a shipment of dangerous goods?</description>
        <label>Dangerous Goods</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Del_Postcode__c</fullName>
        <description>PCOD from GB Mailer</description>
        <label>Delivery Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enhanced_Liability__c</fullName>
        <description>The Tier/Level of Enhanced Liability selected by the customer for a Booking/Quote 
&quot;Account level&quot; should be forced and value not selectable if Transit Liability Charge and Transit Liability Value is set on Account LOB record</description>
        <inlineHelpText>EL not available for precious stones, precious metals, laptop computers, plasma and LCD screens, jewellery, money, glass, china, objects of art, antiques, documents or any films, tapes, discs, memory cards or any such other data or image carrying goods.</inlineHelpText>
        <label>Enhanced Liability</label>
        <picklist>
            <picklistValues>
                <fullName>0 - None</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1 - £4.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - £7.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - £10.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OC_First_Name__c</fullName>
        <label>Order Contact First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OC_Last_Name__c</fullName>
        <label>Order Contact Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OC_Phone_Number__c</fullName>
        <label>Order Contact Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Order_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings (Order Contact)</relationshipLabel>
        <relationshipName>OC_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Quote must belong to the same Account as the booking</errorMessage>
            <filterItems>
                <field>Quote__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Booking_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Booking Line Items</relationshipLabel>
        <relationshipName>Booking_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <description>Field to save one item&apos;s height in meters</description>
        <inlineHelpText>Item height in meters</inlineHelpText>
        <label>Height (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <description>Field to save one item&apos;s length in meters</description>
        <inlineHelpText>Item length in meters</inlineHelpText>
        <label>Length (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <label>Number of Items</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Field to save one item&apos;s weight in kilograms</description>
        <inlineHelpText>Item weight in kilograms</inlineHelpText>
        <label>Weight (kg)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <description>Field to save one item&apos;s width in meters</description>
        <inlineHelpText>Item width in meters</inlineHelpText>
        <label>Width (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Booking Line Item</label>
    <nameField>
        <displayFormat>Line-{0000}</displayFormat>
        <label>Booking Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Postcode__c.object
<CustomObject>
    <fields>
        <fullName>Postcode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Postcode</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Postcode</label>
    <nameField>
        <label>Postcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Carriage_Forward__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Carriage Forward</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collection_Postcode__c</fullName>
        <description>Collection postcode</description>
        <label>Collection: Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Phone__c</fullName>
        <label>Company Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contact must belong to the same Account as specified on Quote record.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dangerous_Goods__c</fullName>
        <defaultValue>false</defaultValue>
        <description>is this a shipment of dangerous goods?</description>
        <label>Dangerous Goods</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delivery_Postcode__c</fullName>
        <description>Delivery postcode</description>
        <label>Delivery: Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Only__c</fullName>
        <description>email field if matching contact cannot be found</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>No_Long_Length_Items__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Stores the number of Long Length Items that have been entered on the Quote Line Items Over 160cm in any dimension.  This value is calculated within the code on record Edit and is set when the user clicks Save. (See OL_BookingQuoteHelper.cls)</description>
        <label>No. Long Length Items</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>QR{000000}</displayFormat>
        <label>Quote Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Height__c</fullName>
        <description>Field to save one item&apos;s height in meters</description>
        <inlineHelpText>Item height in meters</inlineHelpText>
        <label>Height (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <description>Field to save one item&apos;s length in meters</description>
        <inlineHelpText>Item length in meters</inlineHelpText>
        <label>Length (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <label>Number of Items</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Field to save one item&apos;s weight in kilograms</description>
        <inlineHelpText>Item weight in kilograms</inlineHelpText>
        <label>Weight (kg)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <description>Field to save one item&apos;s width in meters</description>
        <inlineHelpText>Item width in meters</inlineHelpText>
        <label>Width (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>Line-{0000}</displayFormat>
        <label>Quote Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OL_BookingQuoteHelper.cls
/**
* File Name   :    OL_BookingQuoteHelper.cls
* Description :    
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 08/07/2014 Klea Kolaric   Initial version
* 0.2 16/07/2014 Klea Kolaric   TNT-476,TNT-477
* 0.3 23/07/2014 Liza Romanenko TNT-532, TNT-609
* 0.4 05/08/2014 Klea Kolaric   TNT-1293
* 0.5 05/08/2014 Liza Romanenko TNT-1326
* 0.6 06/08/2014 Liza Romanenko TNT-1329
* 0.7 19/08/2014 Klea Kolaric   TNT-1560    this extension will only be used for Quotes from now on, instead of both quote and booking
* 0.8 10/10/2014 Klea Kolaric   TNT-2030    mimic address behaviour from Bookings
* 0.9 17/10/2014 Klea Kolaric   TNT-2218    quote shouldn't save if line items fail
* 0.10 14/07/2015 Darryl Hopper             added getNumLongItems from line 361 and 255 to update No_LongLengthITems field
*/
public with sharing class OL_BookingQuoteHelper {
    
    public Id newId {
        get{
            return '000000000000000000';    // faulty Id to signal that we want new record
        }
        private set;
    }
    
    private sObject record;
    public Account currentAccount {get; set;}
    /* public Boolean createContact {get; set;} */
    private String oldRecordId;
    private String bId;
    public Boolean hadAccount {get; private set;}    // assert if record had account on load - glitch fix
    public List<Quote_Line_Item__c> quoteItems {get; set;}
    public List<Quote_Line_Item__c> delQuoteItems {get; set;}
    public String aaDefPC {get; private set;}
    public Boolean hasContactEmail {get; set;}
    
    public OL_BookingQuoteHelper(Apexpages.standardController stdCtrl)
    {
        record = stdCtrl.getRecord();
        hadAccount = ((Id) record.get('Id')) != null && ((Id) record.get(ConstantUtil.FLD_ACCOUNT_APINAME)) != null;
        //clone old record for editing
        oldRecordId = ApexPages.currentPage().getParameters().get('oId');
        bId = ApexPages.currentPage().getParameters().get('bId');
        copyDataFromBooking();
        if(!String.isEmpty(oldRecordId)){
            cloneRecord();
        }
        
        if(record instanceof Quote__c){
            initQuoteLines();
        }
        
        Id accountId = (Id) record.get(ConstantUtil.FLD_ACCOUNT_APINAME);
        if(accountId != null)
        {
            currentAccount = new Account(id = accountId);   // referencing account field in page gives null always for soem reason :(
            if(((Id) record.get('id')) == null && String.isBlank(oldRecordId) && String.isBlank(bId))
            {
                resetAddresses();
            }
        }
        findContactEmail();
    }
    
    public void resetAddresses()
    {
        findCurrentAccount();
        removeAddresses();
        if(record instanceof Quote__c)
        {
            Quote__c q = (Quote__c) record;
            q.Collection_Postcode__c = aaDefPC;
        }
    }
    
    public void collectionPostcodeChanged()
    {
        if(String.isNotBlank(aaDefPC))
        {
            if(record instanceof Quote__c)
            {
                Quote__c q = (Quote__c) record;
                if(q.Collection_Postcode__c != aaDefPC)
                {
                    q.Delivery_Postcode__c = aaDefPC;
                    q.Carriage_Forward__c = true;
                }
                else
                {
                    q.Carriage_Forward__c = false;
                    if(q.Delivery_Postcode__c == aaDefPC)
                    {
                        q.Delivery_Postcode__c = null;
                    }
                }
            }
        }
    }
    
    public void clearAccount()
    {
        currentAccount = null;
        aaDefPC = null;
        record.put(ConstantUtil.FLD_ACCOUNT_APINAME,null);
        removeAddresses();
    }
    
    public void removeAddresses()
    {
        if(record instanceof Quote__c)      // reset address fields
        {
            for(Schema.FieldSetMember fsm : sObjectType.Quote__c.FieldSets.AddressFields.getFields())
            {
                if(fsm.getType() == Schema.DisplayType.String)
                {
                    record.put(fsm.getFieldPath(),null);
                }
                else
                {
                    if(fsm.getType() == Schema.DisplayType.Boolean)
                    {
                        record.put(fsm.getFieldPath(),false);
                    }
                }
            }
        }
    }
    
    public void findCurrentAccount()
    {
        Id accountId = (Id) record.get(ConstantUtil.FLD_ACCOUNT_APINAME);
        currentAccount = accountId == null ? new Account() : 
            (Account) FieldSetUtil.queryViaFieldSet(
                        sObjectType.Account.FieldSets.AccountInfoFields.getFields(),
                        sObjectType.Account.getName(),
                        'Id = \'' + accountId + '\'').get(0);
        // this could have been done as an account child query but Im trying to keep the code interventions to a minimum
        aaDefPC = null;
        for(Account_Address__c aa : [select Postcode__c from Account_Address__c where Default__c = true and Account__c = :accountId])
        {
            aaDefPC = aa.Postcode__c;
            break;
        }
    }
    
    public String getOnStopURL()
    {
        Id accountId = (Id) record.get(ConstantUtil.FLD_ACCOUNT_APINAME);
        return Page.OL_AccountOnStopSubmitAgent.getUrl() + '?id=' + accountId;
    }
    
    public void findContactEmail()
    {
        Id contactId = (Id) record.get(ConstantUtil.FLD_CONTACT_APINAME);
        if(contactId != null)
        {
            Boolean hasEmail = [select count() from Contact where id = :contactId and Email != null] > 0;
            if(hasEmail)
            {
                record.put('Email_Only__c',null);
            }
            hasContactEmail = hasEmail;
        }
        else
        {
            hasContactEmail = false;
        }
    }
    
    public void emptyAction() {}
    
    
    public Boolean processNewAccount(Id accountId)
    {
        // remove fields if an account selected
        if(accountId != null)
        {
            List<Schema.FieldSetMember> fsms = sObjectType.Quote__c.FieldSets.CompanyFields.getFields();
            for(Schema.FieldSetMember fsm : fsms)
            {
                record.put(fsm.getFieldPath(),null);
            }
        }
        else
        {
            String errorMsg = FieldSetUtil.checkRequiredFieldsFS(record,sObjectType.Quote__c.FieldSets.CompanyFields.getFields());
            if(String.isNotBlank(errorMsg))
            {
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR,errorMsg));
                return false;
            }
        }
        return true;
    }
    
    public Boolean processNewContact(Id contactId)
    {
        // if no contact selected agent should populate contact fields
        if(contactId == null)
        {
            String errorMsg = FieldSetUtil.checkRequiredFieldsFS(record,sObjectType.Quote__c.FieldSets.ContactFields.getFields());
            if(String.isNotBlank(errorMsg))
            {
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR,errorMsg));
                return false;
            }
        }
        else
        {
            // remove fields if an contact selected
            List<Schema.FieldSetMember> fsms = sObjectType.Quote__c.FieldSets.ContactFields.getFields();
            for(Schema.FieldSetMember fsm : fsms)
            {
                record.put(fsm.getFieldPath(),null);
            }
        }
        return true;
    }
    
    public Pagereference customSave()
    {
        Id accountId = (Id) record.get(ConstantUtil.FLD_ACCOUNT_APINAME);
        Id contactId = (Id) record.get(ConstantUtil.FLD_CONTACT_APINAME);
        
        // process additional objects/fields
        Boolean noErrors = true;
        noErrors &= confirmHasQuoteLineItems();
        noErrors &= processNewAccount(accountId);
        noErrors &= processNewContact(contactId);
        if(!noErrors)
        {
            return null;    // if error while processing, refresh page
        }
        
        Savepoint sp = Database.setSavepoint();
        Boolean isNew = ((Quote__c) record).id == null;
        try
        {
            // check if required fields for object have been set
            String errorMsg = FieldSetUtil.checkRequiredFieldsFS(record,sObjectType.Quote__c.FieldSets.EditFields.getFields());
            if(record instanceof Quote__c){
                errorMsg += FieldSetUtil.checkRequiredFieldsFS(record, sObjectType.Quote__c.FieldSets.AddressFields.getFields());
            }
            if(String.isNotBlank(errorMsg))
            {
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR,errorMsg));
                return null;
            }
            // if everything ok insert object
            
            //DH
            record.put(Quote__c.No_Long_Length_Items__c,getNumLongLengths());

            
            upsert record;
            
            //check if it has been copied from Booking and update Booking
            if(bookFrom != null){
                bookFrom.Quote__c = record.Id;
                update bookFrom;
            }
            
            if(record instanceof Quote__c){
                saveQuoteLines();
            }
        }
        catch(DmlException ex)
        {
            ApexPages.addMessages(ex);
            if(((Quote__c) record).id != null && isNew) // don't save quote without items
            {
                Database.rollback(sp);  // if you saved quote but got an exception, it means something is wrong with line items
                record.put('id',null);  // remove the id if it was set by the save
            }
            return null;
        }
        return new Pagereference('/' + (String) record.get('Id'));
    }
    
    //Method to clone old Quote or Booking while editing 
    private void cloneRecord(){
        String objectType = '';
        Schema.sObjectType objType;
        Schema.DescribeSObjectResult res;
        if(record instanceof Quote__c){
            objType = Quote__c.sObjectType;
        } else {
            objType = Booking__c.sObjectType;
        }
        
        res = objType.getDescribe();        
        Map<String , Schema.SObjectField> mapFieldList = res.fields.getMap();
        Schema.SObjectField[] fields = mapFieldList.values();
        
        String qry = getSoqlAllFieldsForObject(objType) + ' WHERE Id = \''+oldRecordId+'\'';
        sObject oldObj = Database.query(qry);
        
        List<Schema.FieldSetMember> allFields = SObjectType.Quote__c.FieldSets.EditFields.getFields();
        allFields.addAll(SObjectType.Quote__c.FieldSets.AddressFields.getFields());
        for(Schema.FieldSetMember f : allFields) {
            if(f.getFieldPath() != 'Name'){
                record.put(f.getFieldPath(), oldObj.get(f.getFieldPath()));
            }
        }
    }
    
    //Method to clone Booking and Quiote lines
    /*private void cloneLines(){
        String objectType, parentType;
        String qry;
        Schema.sObjectType objType;
        objType = Booking_Line_Item__c.sObjectType;
        parentType = 'Booking__c';
        
        qry = getSoqlAllFieldsForObject(objType) + ' WHERE ' + parentType + ' = \''+oldRecordId+'\'';
        
        List<sObject> newLines = new List<sObject>();
        for(sObject so : Database.query(qry)){
            sObject nSo = so.clone(false, true);
            nSo.put(parentType, record.Id);
            newLines.add(nSo);
        }
        
        insert newLines;
        
    }*/
    
    //TNT-1329 Add Quote lines to the same edit page with Quote
    private void initQuoteLines(){
        quoteItems = new List<Quote_Line_Item__c>();
        delQuoteItems = new List<Quote_Line_Item__c>();
        
        String qId = (record.Id == null ? oldRecordId : record.Id);
        
        if(qId != null){
            String qry;
            qry = getSoqlAllFieldsForObject(Quote_Line_Item__c.sObjectType) + ' WHERE Quote__c ' + ' = \''+qId+'\'';
            
            for(Quote_Line_Item__c so : Database.query(qry)){
                Quote_Line_Item__c nSo = so;
                if(oldRecordId != null){
                    nSo = so.clone(false, true);
                }
                quoteItems.add(nSo);
            }
        } else if(!String.isBlank(bId)){
            for(Booking_Line_Item__c bli : [SELECT Height__c, Length__c, Number_of_Items__c, Weight__c, Width__c 
                                            FROM Booking_Line_Item__c WHERE Booking__c = : bId]){
                Quote_Line_Item__c qli = new Quote_Line_Item__c();
                qli.Height__c = bli.Height__c;
                qli.Length__c = bli.Length__c;
                qli.Number_of_Items__c = bli.Number_of_Items__c;
                qli.Weight__c = bli.Weight__c;
                qli.Width__c = bli.Width__c;
                
                quoteItems.add(qli);
            }
        } else {
            quoteItems.add(new Quote_Line_Item__c());
        }
    }
    
    //DH
    public decimal getNumLongLengths()
    {
            Decimal count = 0;
                
            for(Quote_Line_Item__c qi : quoteItems)
            {
                if(qi.Length__c > 160 || qi.Width__c > 160 || qi.Height__c > 160)
                {
                    count += qi.Number_of_Items__c == null ? 0:qi.Number_of_Items__c;
                }
                    
            }
        
            return count;
            
    }
    
    
    public PageReference RefreshDarryl()
    {
        //getNumLongLengths();
        return null;
    }

    
    // TNT-1928 check that at least one non-void line item exists
    private Boolean confirmHasQuoteLineItems()
    {
        List<Schema.FieldSetMember> qliFields = SObjectType.Quote_Line_Item__c.FieldSets.EditFields.getFields();
        if(!quoteItems.isEmpty())
        {
            for(Quote_Line_Item__c qli : quoteItems)
            {
                if(!checkObjIsEmpty(qli, qliFields))
                {
                    return true;
                }
            }
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR,
                'At least one line item must be valid: all fields cannot be blank or 0.'));
        }
        else
        {
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR,'You must enter at least one line item.'));
        }
        return false;
    }
    
    //Method saved modified or new lines and delete deleted lines
    private void saveQuoteLines(){
        List<Quote_Line_Item__c> linesToDelete = new List<Quote_Line_Item__c>();
        List<Quote_Line_Item__c> linesToSave = new List<Quote_Line_Item__c>();
        Boolean hasData;
        List<Schema.FieldSetMember> qliFields = SObjectType.Quote_Line_Item__c.FieldSets.EditFields.getFields();
        
        for(Quote_Line_Item__c qli : quoteItems){
            if(qli.Id == null){
                qli.Quote__c = record.Id;
            }
            //check if data is entered
            if(!checkObjIsEmpty(qli, qliFields)){
                linesToSave.add(qli);
            } else if(qli.Id != null){
                linesToDelete.add(qli);
            }
        }
        
        if(!linesToSave.isEmpty()){
            upsert linesToSave;
        }
        
        for(Quote_Line_Item__c qli : delQuoteItems){
            if(qli.Id != null){
                linesToDelete.add(qli);
            }
        }
        
        if(!linesToDelete.isEmpty()){
            delete linesToDelete;
        }
    }
    
    //Method adds line to Quotelines table
    public void addLine(){
        quoteItems.add(new Quote_Line_Item__c());
    }
    
    //Method removes line from Quote lines table
    public void removeLine(){
        Integer rowIndex = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
        Quote_Line_Item__c del = quoteItems.remove(rowIndex);
        delQuoteItems.add(del);
    }
    
    /* COPY DATA FROM BOOKING */
    private Booking__c bookFrom;
    
    public void copyDataFromBooking(){
        if(!String.isBlank(bId) && record.Id == null){
            bookFrom = [SELECT Account__c, Coll_Postcode__c, Del_Postcode__c, Enhanced_Liability__c, 
                                Dangerous_Goods__c, Carriage_Forward__c, Company_Name__c, Company_Phone__c, 
                                Order_Contact__c, OC_First_Name__c, OC_Last_Name__c, OC_Phone_Number__c,
                                OC_Email_Address__c, Collection_Ready_Time__c, Goods_Description__c
                               FROM Booking__c WHERE Id = : bId];
                               
            Quote__c qt = (Quote__c)record;
                               
            qt.Account__c = bookFrom.Account__c;
            qt.Company_Name__c = bookFrom.Company_Name__c;
            qt.Company_Phone__c = bookFrom.Company_Phone__c;
            
            qt.Contact__c = bookFrom.Order_Contact__c;
            qt.Contact_First_Name__c = bookFrom.OC_First_Name__c;
            qt.Contact_Last_Name__c = bookFrom.OC_Last_Name__c;
            qt.Contact_Phone__c = bookFrom.OC_Phone_Number__c;
            qt.Contact_Email__c = bookFrom.OC_Email_Address__c;
            
            qt.Collection_Postcode__c = bookFrom.Coll_Postcode__c;
            qt.Delivery_Postcode__c = bookFrom.Del_Postcode__c;
            qt.Enhanced_Liability_Option__c = bookFrom.Enhanced_Liability__c;
            qt.Dangerous_Goods__c = bookFrom.Dangerous_Goods__c;
            qt.Carriage_Forward__c = bookFrom.Carriage_Forward__c;
            qt.Collection_Date__c = (bookFrom.Collection_Ready_Time__c != null ?  bookFrom.Collection_Ready_Time__c.date() : null);
            qt.Items_Description__c = bookFrom.Goods_Description__c;
        }
    }
    
    /* STATIC */
    
    public static String getSoqlAllFieldsForObject(Schema.sObjectType objType){
        String res = '';
        
        Schema.DescribeSObjectResult describeRes = objType.getDescribe();
        
        String expr = getAllFieldsForObject(describeRes);
        res = expr + ' from ' + describeRes.getName();
        
        return res;
    }
    
    public static String getAllFieldsForObject(Schema.DescribeSObjectResult describeRes){
        String res = '';
        Map<String , Schema.SObjectField> mapFieldList = describeRes.fields.getMap();
        Schema.SObjectField[] fields = mapFieldList.values();
        String expr = '';
        for( Integer i=0; i < fields.size()-1; i++ )
        {
            Schema.DescribeFieldResult fieldResult = fields[i].getDescribe();
            expr += fieldResult.getName() + ', ';
        }
        Schema.DescribeFieldResult fieldResult = fields[fields.size() - 1].getDescribe();
        expr += fieldResult.getName();
        
        res = 'Select ' + expr;
        
        return res;
    }
    
    //Check if any data have been added to object
    public static Boolean checkObjIsEmpty(sObject obj, List<Schema.FieldSetMember> fieldsList){
        Boolean res = true;
        
        for(Schema.FieldSetMember f : fieldsList){
            if(obj.get(f.getFieldPath()) != null && obj.get(f.getFieldPath()) != '' && obj.get(f.getFieldPath()) != false
                && (f.getType() != Schema.DisplayType.Double || ((double) obj.get(f.getFieldPath())) != 0))
            {
                res = false;
                break;
            }
        }
        
        return res;
    }
}