objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Action_Subtype__c</fullName>
        <label>Action Subtype</label>
        <picklist>
            <controllingField>Action_Type__c</controllingField>
            <picklistValues>
                <fullName>Apology Letter Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consignment Downgraded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free Replacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice Suppression</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice Reduced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Aways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Customer Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Depot Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forwarded to Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preliminary Checks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRU Instructed to Start Searches</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day 1 Searches</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day 2 Searches</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day 3 Searches</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Searches Checked - Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Searches Checked - Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C File Raised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SLA_Deadline__c</fullName>
        <label>SLA Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SLA_Minutes_in_Business_Hours__c</fullName>
        <description>Work Out Business Hours between. Business Hours are taken from Company Settings</description>
        <label>SLA Minutes (Business Hours)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TaskTriggerHandler.cls
/**
* File Name   :    TaskTriggerHandler.cls
* Description :    methods called from Task trigger
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 13/04/2015 Liza Romanenko	Initial version (TNT-2697)
*
*/
public with sharing class TaskTriggerHandler {
	// HANDLERS
	
	public static void onBeforeInsertHandler(List<Task> triggerNew)
	{
		calculateSLAInBussinessHours(triggerNew);
	}
	
	public static void onBeforeUpdateHandler(List<Task> triggerNew)
	{
		calculateSLAInBussinessHours(triggerNew);
	}
	
	// METHODS
	
	private static void calculateSLAInBussinessHours(List<Task> newTasks){
		
		for(Task t : newTasks){
			// When should we calculate activity age
			if((t.Action_Subtype__c == ConstantUtil.PLVAL_TASK_ACTION_SUBTYPE_FIRST_CUSTOMER_CONTACT 
						|| t.Action_Subtype__c == ConstantUtil.PLVAL_TASK_ACTION_SUBTYPE_CUSTOMER_CONTACT) 
						&& t.SLA_Deadline__c != null && t.End_Time__c != null){
				
				t.SLA_Minutes_in_Business_Hours__c = TimeUtil.calculateMinutesInBusinessHours(t.Start_Time__c, t.End_Time__c);
			}
		}
		
	}

}