objects/Booking_History__c.object
<CustomObject>
    <fields>
        <fullName>Movement_Date_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Movement Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Booking History</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Booking History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking History Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/DataRetentionSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Used to set the number of days object records are stored for before they are deleted by a Scheduled Apex Job. See BookingHistory_DataDeletion Apex Class for example.

If the retention period is set to 90 days and 90 days before today is calculated to be 1st January 2016, any code should be developed to delete data from this date or older than this.</description>
    <fields>
        <fullName>BookingHistoryRetentionPeriod__c</fullName>
        <defaultValue>365</defaultValue>
        <description>The Default Value sets how long the Booking History records are stored for in Salesforce. Records whose Movement Date/Time are older than this amount of days will be deleted on a scheduled basis.</description>
        <label>Booking History Retention Period</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Data Retention Settings</label>
</CustomObject>

classes/BookingHistory_DataDeletion.cls
global class BookingHistory_DataDeletion implements Schedulable 
{
   global void execute(SchedulableContext sc) 
   {
        BatchDelete BDel = new BatchDelete(); 
        Integer  no  = 0;  
        DataRetentionSettings__c myCS1 = DataRetentionSettings__c.getInstance('DayNumber'); 
        if (myCS1 != null)
        {       
            System.debug(logginglevel.ERROR, '££££££££££££££ no is' + myCS1.BookingHistoryRetentionPeriod__c);          
            no = myCS1.BookingHistoryRetentionPeriod__c.intValue();       
        }
        else
        {
            no = 180;
        }             

        datetime ddd = SYSTEM.NOW().addDays(-no);
        System.debug(logginglevel.ERROR, '££££££££££££££ ddd is' + ddd );  
   //     BDel.query = 'SELECT Id FROM Booking_History__c where Movement_Date_Time__c < 2015-04-22T13:31:00.00Z';
      
        BDel.query = 'SELECT Id FROM Booking_History__c where Movement_Date_Time__c < '+ddd.format('yyyy-MM-dd')+'T'+ ddd.format('HH:mm')+':00.000Z'; 
        ID batchprocessid = Database.executeBatch(BDel); 


        System.debug('************************** Returned batch process ID: ' + batchProcessId); 
   }
}