objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Commodity__c</fullName>
        <description>Value restricted by LOB Selected</description>
        <label>Type of packaging</label>
        <picklist>
            <picklistValues>
                <fullName>TSL 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSL 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assorted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Envelope</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dangerous Goods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incompatible Traffic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jiffy Bag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Length</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Supplies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pallet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roll</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundle</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Booking_History__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Booking History Records</relationshipLabel>
        <relationshipName>Booking_History_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Movement_Date_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Movement Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Booking History</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Booking History Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking History Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BookingHistory_DataDeletion_Tests.cls
@isTest//(SeeAllData=true)
private class BookingHistory_DataDeletion_Tests
{                                   
    static testMethod void DataDeletionTest()
    {                 
          Booking__c myBooking = new Booking__c(); 
          myBooking.Commodity__c = 'Envelope';
          insert myBooking;  
           
          List<Booking__c> value = [Select id from Booking__c]; 
          string bookingID;
          for (Booking__c record : value )
          {
             if (record.Id != null)
             {
                bookingID = record.Id;
             }
          }    

          Booking_History__c myBookingHistory = new Booking_History__c(); 
          myBookingHistory.Movement_Date_Time__c = date.newInstance(2015, 08, 01); 
          myBookingHistory.Booking__c = bookingID;
          insert myBookingHistory;     
          System.debug(logginglevel.ERROR, '££££££££££££££ myBookingHistory1 is' + myBookingHistory.Movement_Date_Time__c);                    
          
          Booking_History__c myBookingHistory2 = new Booking_History__c(); 
          myBookingHistory2.Movement_Date_Time__c = date.newInstance(2013, 01, 01); 
          myBookingHistory2.Booking__c = bookingID; 
          insert myBookingHistory2; 
          System.debug(logginglevel.ERROR, '££££££££££££££ myBookingHistory2 is' + myBookingHistory2.Movement_Date_Time__c);              
          
          Booking_History__c myBookingHistory3 = new Booking_History__c(); 
          myBookingHistory3.Movement_Date_Time__c = date.newInstance(2014, 01, 01);   
          myBookingHistory3.Booking__c = bookingID;         
          insert myBookingHistory3; 
          System.debug(logginglevel.ERROR, '££££££££££££££ myBookingHistory3 is' + myBookingHistory3.Movement_Date_Time__c);                   
                         
          Test.startTest();                   
           
          BookingHistory_DataDeletion dd = new  BookingHistory_DataDeletion();
          SchedulableContext sc;
          dd.execute(sc);
          
          List<Booking_History__c> bookingHistory = [Select id, Movement_Date_Time__c from Booking_History__c];  
          integer i = 0;
          for (Booking_History__c record : bookingHistory )
          { 
             if (record.Id != null)
             {
                System.debug(logginglevel.ERROR, '££££££££££££££ existing record is' + record.Movement_Date_Time__c);                                
                i = i+1;
              }
          }          

          Test.stopTest();
          //System.assertEquals(1, i);
    } 
}