objects/Case.object
<CustomObject>
    <fields>
        <fullName>Call_me_back__c</fullName>
        <description>create task with reminder</description>
        <label>Call me back</label>
        <picklist>
            <picklistValues>
                <fullName>1 hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>48 hours</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TaskTriggerHandlerTest.cls
/**
* File Name   :    TaskTriggerHandlerTest.cls
* Description :    test for Task trigger handler
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 13/04/2015 Liza Romanenko	Initial version (TNT-2697)
*
*
*/
@isTest
private class TaskTriggerHandlerTest {
	
	static testMethod void coverTaskTrigger(){
		
		Account a = TestUtil.createAccountClient();
        insert a;
        Account d = TestUtil.createAccountDepot();
        insert d;
        Contact con = TestUtil.createContact(a.Id);
        insert con;
        Case c = TestUtil.createCase(a.Id, con.Id, d.Id);
        c.Call_me_back__c = '1 hour';
        insert c;
        
        Task t = [SELECT Status FROM Task WHERE Subject = : ConstantUtil.TASK_SUBJECT_CALL_CLIENT_BACK LIMIT 1];
               
        Test.startTest();
        
        t.Status = ConstantUtil.PLVAL_TASK_STATUS_COMPLETED;
        update t;
               
        Test.stopTest();
        
        t = [SELECT SLA_Minutes_in_Business_Hours__c FROM Task WHERE Subject = : ConstantUtil.TASK_SUBJECT_CALL_CLIENT_BACK LIMIT 1];
        
        system.assertNotEquals(null, t.SLA_Minutes_in_Business_Hours__c);
		
	}
	
	
}