objects/CS_Claims__c.object
<CustomObject>
    <description>TNT UK Claims Form Attachment Handling SR 2751</description>
    <fields>
        <fullName>All_requested_information__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All requested information</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Claims_Stage__c</fullName>
        <label>Claims Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Consignment_no__c</fullName>
        <label>Consignment no</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copy_of_relevant_commercial_invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>A copy of relevant commercial invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Copy_of_repair_estimate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>A copy of repair estimate/invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost_of_consignment_exclcuding_VAT__c</fullName>
        <label>Cost value of consignment exclcuding VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_of_items_exclcuding_VAT__c</fullName>
        <label>Cost value of item(s) exclcuding VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit_your_TNT_account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit your TNT account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Damaged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Damaged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_dispatch__c</fullName>
        <label>Date of Despatch</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Declarant_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Declarant_Full_Name_of__c</fullName>
        <label>Full name of claimant</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Depot_no__c</fullName>
        <inlineHelpText>Is auto populated from the Depot field when clicking &apos;Save&apos;.</inlineHelpText>
        <label>Depot no</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Detail_description_of_items__c</fullName>
        <label>Detailled description of the item(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lost__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recipient_Address_1__c</fullName>
        <label>Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Address_2__c</fullName>
        <label>Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Address_3__c</fullName>
        <label>Town</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Contact_Name__c</fullName>
        <label>Contact name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Telephone_no__c</fullName>
        <label>Telephone no</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Reference_no__c</fullName>
        <label>Claim Reference no</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repair_cost__c</fullName>
        <label>What is the repair cost?</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Replacement_Consignment_No__c</fullName>
        <label>Replacement consignment no</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salvage_value__c</fullName>
        <label>Salvage value ?</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sender_Address_1__c</fullName>
        <label>Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Address_2__c</fullName>
        <label>Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Address_3__c</fullName>
        <label>Town</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Contact_Name__c</fullName>
        <label>Contact name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Email_Address__c</fullName>
        <inlineHelpText>If the Contact above does not have an Email Address stored for them, you can enter one to use here.

If they do, then leave this field blank as it is auto populated from the Contact when clicking &apos;Save&apos;.</inlineHelpText>
        <label>Customer Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sender_Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Telephone_no__c</fullName>
        <label>Telephone no</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sender_company_name__c</fullName>
        <label>Company name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNT_account_no__c</fullName>
        <inlineHelpText>Is auto populated from the Account field when clicking &apos;Save&apos;.</inlineHelpText>
        <label>TNT account no</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight_of_items__c</fullName>
        <label>Weight of lost/damaged item(s) kg</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cheque__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cheque</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>damaged_packing_inspection__c</fullName>
        <description>Please state where the damaged item(s) and packing can be inspected</description>
        <inlineHelpText>Please state where the damaged item(s) and packing can be inspected</inlineHelpText>
        <label>item(s) and packing can be inspected at</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>photographs_of_the_items__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Brouchers/photographs of the items</label>
        <type>Checkbox</type>
    </fields>
    <label>Claim Form</label>
    <nameField>
        <displayFormat>CLN-{000000}</displayFormat>
        <label>Claim Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CS_TNT_Claims__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Check_list_opt_1__c</fullName>
        <label>Check list opt 1</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_list_opt_2__c</fullName>
        <label>Check list opt 2</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_list_opt_3__c</fullName>
        <label>Check list opt 3</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_list_opt_4__c</fullName>
        <label>Check list opt 4</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claims_damaged_section_title__c</fullName>
        <label>Claims damaged section Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claims_postal_address__c</fullName>
        <label>Claims postal address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Claims_type_details_section_content__c</fullName>
        <label>Claims type details section Content</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Claims_type_details_section_title__c</fullName>
        <label>Claims type details section Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Claims_type_fieldset_label__c</fullName>
        <label>Claims type fieldset label</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_value_of_consignment_label__c</fullName>
        <label>Cost value of consignment label</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_value_of_items_label__c</fullName>
        <label>Cost value of items label</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Declaration_section_title__c</fullName>
        <label>Declaration section Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Id__c</fullName>
        <label>Email Id</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Header__c</fullName>
        <label>Header</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Method_of_payment_fieldset_label__c</fullName>
        <label>Method of payment fieldset label</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Section_title__c</fullName>
        <label>Recipient Section  Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Replacement_consignment_no_Label__c</fullName>
        <label>Replacement consignment no Label</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sender_section_title__c</fullName>
        <label>Sender section Title</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>damaged_items_inspection_label__c</fullName>
        <label>damaged items inspection Label</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TNT UK Claims</label>
</CustomObject>

classes/CS_Claims_Form_PDF_Controller.cls
/**
This controller is used for the PDF creation, for Claims email-templates.
**/

public with sharing class CS_Claims_Form_PDF_Controller {
    
    public CS_Claims__c claims {get; set;}
    
    public Id claimId {     
        get; 
        
        set{
                if(value != null){
                claims = getClaims(value);
                }
        }
    }
         
       public String emailId {
                get{
                        return CS_TNT_Claims__c.getInstance().Email_Id__c; 
                }
       } 
       public String address {
                get{
                        return CS_TNT_Claims__c.getInstance().Claims_postal_address__c; 
                }
       }
       public String header {
                get{
                        return CS_TNT_Claims__c.getInstance().Header__c;
                }
       }        
       
       public String Sender_section_title{
                get{
                        return CS_TNT_Claims__c.getInstance().Sender_section_title__c;
                }
       }
       public String Recipient_section_title{
                get{
                        return CS_TNT_Claims__c.getInstance().Recipient_Section_title__c;
                }
       }
       public String Claims_type_fieldset_label{
                get{
                        return CS_TNT_Claims__c.getInstance().Claims_type_fieldset_label__c;
                }
       }                                                 
       public String Claims_type_details_section_title{
                get{
                        return CS_TNT_Claims__c.getInstance().Claims_type_details_section_title__c;
                }
       }
       public String Claims_type_details_section_content{
                get{
                        return CS_TNT_Claims__c.getInstance().Claims_type_details_section_content__c;
                }
       }
       public String Claims_damaged_section_title{
                get{
                        return CS_TNT_Claims__c.getInstance().Claims_damaged_section_title__c;
                }
       }       
       public String damaged_items_inspection_label{
                get{
                        return CS_TNT_Claims__c.getInstance().damaged_items_inspection_label__c;
                }
       }
       public String payment_method_label{
                get{
                        return CS_TNT_Claims__c.getInstance().Method_of_payment_fieldset_label__c;
                }
       }
       
       public String Declaration_section_title{
                get{
                        return CS_TNT_Claims__c.getInstance().Declaration_section_title__c;
                }
       }
       public String Cost_value_of_consignment_label{
                get{
                                return CS_TNT_Claims__c.getInstance().Cost_value_of_consignment_label__c;
                }
       }
       public String Cost_value_of_items_label{
                get{
                        return CS_TNT_Claims__c.getInstance().Cost_value_of_items_label__c;
                }
       }
       
       public String check_list_opt_1{
                get{
                                return CS_TNT_Claims__c.getInstance().Check_list_opt_1__c;
                }
       }
       public String check_list_opt_2{
                get{
                                return CS_TNT_Claims__c.getInstance().Check_list_opt_2__c;
                }
       }
       public String check_list_opt_3{
                get{
                                return CS_TNT_Claims__c.getInstance().Check_list_opt_3__c;
                }
       }
       public String check_list_opt_4{
                get{
                                return CS_TNT_Claims__c.getInstance().Check_list_opt_4__c;
                }
       }
       public String replacement_consignement_no_label{
                get{
                        return CS_TNT_Claims__c.getInstance().Replacement_consignment_no_Label__c;
                }
       }    
    public CS_Claims_Form_PDF_Controller(){
     
     	claims = getClaims(Apexpages.currentPage().getParameters().get('cid'));
     	system.debug('==>CLAIMSPDF ' + claims);                                 
    }
    
      public CS_Claims__c getClaims(Id id){
                CS_Claims__c cl = new CS_Claims__c();
                try{
                cl = [SELECT
                        Name,
                        Copy_of_relevant_commercial_invoice__c, 
                        Copy_of_repair_estimate__c,
                        Sender_Address_1__c,
                        Recipient_Address_1__c,
                        Sender_Address_2__c,
                        Recipient_Address_2__c,
                        Sender_Address_3__c,
                        Recipient_Address_3__c,
                        All_requested_information__c,
                        cheque__c,
                        Claims_Stage__c,
                        Sender_company_name__c,
                        Consignment_no__c,
                        Sender_Contact_Name__c,
                        Recipient_Contact_Name__c,
                        Cost_of_consignment_exclcuding_VAT__c,
                        Cost_of_items_exclcuding_VAT__c,
                        Credit_your_TNT_account__c,
                        Sender_Email_Address__c,
                        Damaged__c,
                        Declarant_Date__c,
                        Date_of_dispatch__c,
                        Depot_no__c,
                        Detail_description_of_items__c,
                        Declarant_Full_Name_of__c,
                        damaged_packing_inspection__c,
                        Lost__c,
                        photographs_of_the_items__c,
                        Sender_Postcode__c,
                        Recipient_Postcode__c,
                        Reference_no__c,
                        Salvage_value__c,
                        Sender_Telephone_no__c,
                        Recipient_Telephone_no__c,
                        TNT_account_no__c,
                        Weight_of_items__c,
                        Repair_cost__c,
                        Replacement_Consignment_No__c                                                                                   
                        FROM CS_Claims__c 
                                WHERE 
                                id=: id
                        ];
                }catch(Exception e){
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'If this error persists please contact TNT Customer care for further help. ERROR:' + e.getMessage()));
                }
                        
                        return cl;              
        }
}