objects/Line_of_Business__c.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business_Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique reference for the line of Business.</description>
        <externalId>true</externalId>
        <label>Line of Business Reference</label>
        <length>3</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Line of Business</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines of Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Service_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique code of the Service.</description>
        <externalId>true</externalId>
        <label>Service Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OL_CodeForObjectUtil.cls
/**
* File Name   :    OL_CodeForObjectUtil.cls
* Description :    
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 09/09/2014 Liza Romanenko	Initial version, TNT-546
*/
public with sharing class OL_CodeForObjectUtil {
	
	public static String delimitedServiceCodes {get; set;}
	public static String delimitedLobCodes {get; set;}

	public static Map<String, String> getLineOfBusinesMap(){
		Map<String, String> res = new Map<String, String>();
		delimitedLobCodes = '';
		
		for(Line_of_Business__c lob : [SELECT Name, Line_of_Business_Reference__c FROM Line_of_Business__c]){
			res.put(lob.Line_of_Business_Reference__c, lob.Name);
			delimitedLobCodes += '*' + lob.Line_of_Business_Reference__c + '*';
		}
		
		return res;
	}
	
	public static Map<String, String> getServiceMap(){
		Map<String, String> res = new Map<String, String>();
		delimitedServiceCodes = '';
		
		for(Service__c s : [SELECT Name, Service_Code__c FROM Service__c]){
			res.put(s.Service_Code__c, s.Name);
			delimitedServiceCodes += '*' + s.Service_Code__c + '*';
		}
		
		return res;
	}
}