objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collection_Postcode__c</fullName>
        <description>Collection postcode</description>
        <label>Collection: Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contact must belong to the same Account as specified on Quote record.</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Postcode__c</fullName>
        <description>Delivery postcode</description>
        <label>Delivery: Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Only__c</fullName>
        <description>email field if matching contact cannot be found</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>QR{000000}</displayFormat>
        <label>Quote Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Height__c</fullName>
        <description>Field to save one item&apos;s height in meters</description>
        <inlineHelpText>Item height in meters</inlineHelpText>
        <label>Height (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <description>Field to save one item&apos;s length in meters</description>
        <inlineHelpText>Item length in meters</inlineHelpText>
        <label>Length (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <label>Number of Items</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Field to save one item&apos;s weight in kilograms</description>
        <inlineHelpText>Item weight in kilograms</inlineHelpText>
        <label>Weight (kg)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <description>Field to save one item&apos;s width in meters</description>
        <inlineHelpText>Item width in meters</inlineHelpText>
        <label>Width (cm)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>Line-{0000}</displayFormat>
        <label>Quote Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OL_GetQuotePricingDetailsExtensionTest.cls
/**
* File Name   :    OL_GetQuotePricingDetailsExtensionTest.cls
* Description :    
*
* Modification Log
* ============================================================================
* Ver Date       Author         Modification
* --- ---------- -------------- --------------------------
* 0.1 11/08/2014 Liza Romanenko	Initial version
*
*
*/
@isTest
private class OL_GetQuotePricingDetailsExtensionTest {
	
	static testMethod void testExceptions(){
		Account a = TestUtil.createAccountClient();
		insert a;
		Contact c = TestUtil.createContact(a.Id);
		insert c;
		
		Quote__c qt = new Quote__c();
		qt.Account__c = a.Id;
		qt.Contact__c = c.Id;
		qt.Email_Only__c = 'testmail@gdgfd.tst';
		qt.Collection_Postcode__c = 'aa111a';
		qt.Delivery_Postcode__c = 'aa111a';
    	insert qt;
    	
    	Quote_Line_Item__c qli = new Quote_Line_Item__c();
    	qli.Number_of_Items__c = 1;
		qli.Height__c = 10;
		qli.Length__c = 10;
		qli.Weight__c = 10;
		qli.Width__c = 10;
		qli.Quote__c = qt.Id;
		insert qli;
		
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(qt);
		OL_GetQuotePricingDetailsExtension cont = new OL_GetQuotePricingDetailsExtension(sc);
		
		cont.requestPrice();
		
		List<Apexpages.Message> msgs = ApexPages.getMessages();
		system.assertEquals(1, msgs.size());
		
		cont.savePrice();
		
		msgs = ApexPages.getMessages();
		system.assertEquals(2, msgs.size());
		
		cont.cancel();
    }
    
    static testMethod void testService(){
		Account a = TestUtil.createAccountClient();
		insert a;
		Contact c = TestUtil.createContact(a.Id);
		insert c;
		
		Quote__c qt = new Quote__c();
		qt.Account__c = a.Id;
		qt.Contact__c = c.Id;
		qt.Email_Only__c = 'testmail@gdgfd.tst';
		qt.Collection_Postcode__c = 'aa111a';
		qt.Delivery_Postcode__c = 'aa111a';
		
		Apexpages.Standardcontroller sc = new Apexpages.Standardcontroller(qt);
		OL_GetQuotePricingDetailsExtension cont = new OL_GetQuotePricingDetailsExtension(sc);
		
		Test.startTest();
		
		cont.quote = qt;
		
		Test.setMock(WebServiceMock.class, new uksvcsTntGetQuotePricingServiceMockImpl());
		
		cont.requestPrice();
		
		cont.savePrice();
	
		cont.responceData.del[0].selected = true;
		cont.responceData.del[0].delSvcs.delSvc[0].selected = true;
		
		cont.savePrice();
				
		Test.stopTest();
		
		qt = [SELECT Price__c FROM Quote__c LIMIT 1];
		system.assertEquals(50.45, qt.Price__c);
    }
    
    static testMethod void cover_uksvcsTntComGenericPayloadHeader(){
    	uksvcsTntComGenericPayloadHeader.search_x s = new uksvcsTntComGenericPayloadHeader.search_x();
    } 
    
}